async function Module(moduleArg={}){var moduleRtn;var f=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(ca){const {createRequire:a}=await import("node:module");var require=a(import.meta.url)}f.noInitialRun=!0;var da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=import.meta.url,ia="",ja,ka;
if(ca){var fs=require("node:fs");ha.startsWith("file:")&&(ia=require("node:path").dirname(require("node:url").fileURLToPath(ha))+"/");ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType=
"arraybuffer";b.send(null);return new Uint8Array(b.response)});ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}
var ma=console.log.bind(console),p=console.error.bind(console),na=!1,oa,la=a=>a.startsWith("file://"),pa,qa,r,t,ra,u,v,w,sa=!1;function ta(){var a=ua.buffer;r=new Int8Array(a);ra=new Int16Array(a);t=new Uint8Array(a);new Uint16Array(a);u=new Int32Array(a);v=new Uint32Array(a);new Float32Array(a);new Float64Array(a);w=new BigInt64Array(a);new BigUint64Array(a)}function x(a){a="Aborted("+a+")";p(a);na=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");qa?.(a);throw a;}var va;
async function wa(a){try{var b=await ja(a);return new Uint8Array(b)}catch{}if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){p(`failed to asynchronously prepare wasm: ${d}`),x(d)}}
async function ya(a){var b=va;if(!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){p(`wasm streaming compile failed: ${d}`),p("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=[],Ba=new TextDecoder,Ca=(a,b)=>{for(var c=b+void 0;a[b]&&!(b>=c);)++b;return b},z=a=>a?Ba.decode(t.subarray(a,Ca(t,a))):"",Da=[],Ea=0,B=0;class Fa{constructor(a){this.pb=a;this.za=a-24}Qa(a,b){v[this.za+16>>2]=0;v[this.za+4>>2]=a;v[this.za+8>>2]=b}}
var Ia=a=>{var b=B;if(!b)return Ga(0),0;var c=new Fa(b);v[c.za+16>>2]=b;var d=v[c.za+4>>2];if(!d)return Ga(0),b;for(var e of a){if(0===e||e===d)break;if(Ha(e,d,c.za+16))return Ga(e),b}Ga(d);return b},C=()=>{var a=u[+Ja>>2];Ja+=4;return a},Ka=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},D=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ka(a.split("/").filter(d=>!!d),!b).join("/"))||
b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},La=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},E=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Ma=(...a)=>D(a.join("/")),Na=(a,b)=>D(a+"/"+b),Oa=()=>{if(ca){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Pa=a=>{(Pa=Oa())(a)},Qa=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:F.cwd();if("string"!=
typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ka(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ra=(a,b)=>{function c(h){for(var k=0;k<h.length&&""===h[k];k++);for(var m=h.length-1;0<=m&&""===h[m];m--);return k>m?[]:h.slice(k,m-k+1)}a=Qa(a).slice(1);b=Qa(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");
d=d.concat(b.slice(e));return d.join("/")},Sa=a=>{var b=Ca(a,0);return Ba.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))},Ta=[],Ua=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},H=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(c>=d)break;b[c++]=h}else if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6;b[c++]=128|h&63}else if(65535>=h){if(c+2>=d)break;
b[c++]=224|h>>12;b[c++]=128|h>>6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63;b[c++]=128|h>>6&63;b[c++]=128|h&63;g++}}b[c]=0;return c-e},Va=a=>{var b=Array(Ua(a)+1);a=H(a,b,0,b.length);b.length=a;return b},Wa=[];function Xa(a,b){Wa[a]={input:[],output:[],Ga:b};Ya(a,Za)}
var Za={open(a){var b=Wa[a.node.rdev];if(!b)throw new F.qa(43);a.tty=b;a.seekable=!1},close(a){a.tty.Ga.fsync(a.tty)},fsync(a){a.tty.Ga.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Ga.rb)throw new F.qa(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.Ga.rb(a.tty)}catch(k){throw new F.qa(29);}if(void 0===h&&0===e)throw new F.qa(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Ga.gb)throw new F.qa(60);try{for(var e=0;e<d;e++)a.tty.Ga.gb(a.tty,
b[c+e])}catch(g){throw new F.qa(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},$a={rb(){a:{if(!Ta.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ta=Va(a)}a=Ta.shift()}return a},gb(a,b){null===b||10===b?(ma(Sa(a.output)),a.output=[]):
0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ma(Sa(a.output)),a.output=[])},Mb(){return{Zb:25856,ac:5,Yb:191,$b:35387,Xb:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Nb(){return 0},Ob(){return[24,80]}},ab={gb(a,b){null===b||10===b?(p(Sa(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(p(Sa(a.output)),a.output=[])}},I={Ea:null,ua(){return I.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||F.isFIFO(c))throw new F.qa(63);
I.Ea||(I.Ea={dir:{node:{va:I.ra.va,wa:I.ra.wa,lookup:I.ra.lookup,Ca:I.ra.Ca,rename:I.ra.rename,unlink:I.ra.unlink,rmdir:I.ra.rmdir,readdir:I.ra.readdir,symlink:I.ra.symlink},stream:{xa:I.sa.xa}},file:{node:{va:I.ra.va,wa:I.ra.wa},stream:{xa:I.sa.xa,read:I.sa.read,write:I.sa.write,Ja:I.sa.Ja,Na:I.sa.Na}},link:{node:{va:I.ra.va,wa:I.ra.wa,readlink:I.ra.readlink},stream:{}},mb:{node:{va:I.ra.va,wa:I.ra.wa},stream:F.Db}});c=F.createNode(a,b,c,d);K(c.mode)?(c.ra=I.Ea.dir.node,c.sa=I.Ea.dir.stream,c.ta=
{}):F.isFile(c.mode)?(c.ra=I.Ea.file.node,c.sa=I.Ea.file.stream,c.Aa=0,c.ta=I.Gb??(I.Gb=new Uint8Array(0))):40960===(c.mode&61440)?(c.ra=I.Ea.link.node,c.sa=I.Ea.link.stream):8192===(c.mode&61440)&&(c.ra=I.Ea.mb.node,c.sa=I.Ea.mb.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.ta[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},ra:{va(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;K(a.mode)?b.size=4096:F.isFile(a.mode)?b.size=a.Aa:40960===
(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},wa(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.Aa!=b&&(c=a.ta,a.ta=new Uint8Array(b),a.ta.set(c.subarray(0,Math.min(b,a.Aa))),a.Aa=b))},lookup(){I.Xa||(I.Xa=new F.qa(44),I.Xa.stack="<generic error, no stack>");throw I.Xa;},Ca(a,b,c,d){return I.createNode(a,
b,c,d)},rename(a,b,c){try{var d=L(b,c)}catch(g){}if(d){if(K(a.mode))for(var e in d.ta)throw new F.qa(55);bb(d)}delete a.parent.ta[a.name];b.ta[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.ta[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=L(a,b),d;for(d in c.ta)throw new F.qa(55);delete a.ta[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.ta)]},symlink(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==
(a.mode&61440))throw new F.qa(28);return a.link}},sa:{read(a,b,c,d,e){if(e>=a.node.Aa)return 0;d=Math.min(a.node.Aa-e,d);b.set(a.node.ta.subarray(e,e+d),c);return d},write(a,b,c,d,e,g){b.buffer===r.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(g)a.ta=b.subarray(c,c+d),a.Aa=d;else if(0===a.Aa&&0===e)a.ta=b.slice(c,c+d),a.Aa=d;else{g=e+d;var h=a.ta.length;h>=g||(g=Math.max(g,h*(1048576>h?2:1.125)>>>0),h&&(g=Math.max(g,256)),h=a.ta.subarray(0,a.Aa),a.ta=new Uint8Array(g),a.ta.set(h));
a.ta.set(b.subarray(c,c+d),e);a.Aa=Math.max(a.Aa,e+d)}return d},xa(a,b,c){1===c?b+=a.position:2===c&&F.isFile(a.node.mode)&&(b+=a.node.Aa);if(0>b)throw new F.qa(28);return b},Ja(a,b,c,d,e){if(!F.isFile(a.node.mode))throw new F.qa(43);a=a.node.ta;if(e&2||a.buffer!==r.buffer){d=!0;x();e=void 0;if(!e)throw new F.qa(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);r.set(a,e)}}else d=!1,e=a.byteOffset;return{za:e,Bb:d}},Na(a,b,c,d){I.sa.write(a,b,0,d,
c,!1);return 0}}},cb=a=>{"string"==typeof a&&(a=Va(a));a.subarray||(a=new Uint8Array(a));return a},db=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},eb={EPERM:63,ENOENT:44,ESRCH:71,EINTR:27,EIO:29,ENXIO:60,E2BIG:1,ENOEXEC:45,EBADF:8,ECHILD:12,EAGAIN:6,EWOULDBLOCK:6,ENOMEM:48,EACCES:2,EFAULT:21,ENOTBLK:105,EBUSY:10,EEXIST:20,EXDEV:75,ENODEV:43,ENOTDIR:54,EISDIR:31,EINVAL:28,ENFILE:41,EMFILE:33,ENOTTY:59,ETXTBSY:74,EFBIG:22,ENOSPC:51,ESPIPE:70,EROFS:69,EMLINK:34,EPIPE:64,EDOM:18,ERANGE:68,ENOMSG:49,
EIDRM:24,ECHRNG:106,EL2NSYNC:156,EL3HLT:107,EL3RST:108,ELNRNG:109,EUNATCH:110,ENOCSI:111,EL2HLT:112,EDEADLK:16,ENOLCK:46,EBADE:113,EBADR:114,EXFULL:115,ENOANO:104,EBADRQC:103,EBADSLT:102,EDEADLOCK:16,EBFONT:101,ENOSTR:100,ENODATA:116,ETIME:117,ENOSR:118,ENONET:119,ENOPKG:120,EREMOTE:121,ENOLINK:47,EADV:122,ESRMNT:123,ECOMM:124,EPROTO:65,EMULTIHOP:36,EDOTDOT:125,EBADMSG:9,ENOTUNIQ:126,EBADFD:127,EREMCHG:128,ELIBACC:129,ELIBBAD:130,ELIBSCN:131,ELIBMAX:132,ELIBEXEC:133,ENOSYS:52,ENOTEMPTY:55,ENAMETOOLONG:37,
ELOOP:32,EOPNOTSUPP:138,EPFNOSUPPORT:139,ECONNRESET:15,ENOBUFS:42,EAFNOSUPPORT:5,EPROTOTYPE:67,ENOTSOCK:57,ENOPROTOOPT:50,ESHUTDOWN:140,ECONNREFUSED:14,EADDRINUSE:3,ECONNABORTED:13,ENETUNREACH:40,ENETDOWN:38,ETIMEDOUT:73,EHOSTDOWN:142,EHOSTUNREACH:23,EINPROGRESS:26,EALREADY:7,EDESTADDRREQ:17,EMSGSIZE:35,EPROTONOSUPPORT:66,ESOCKTNOSUPPORT:137,EADDRNOTAVAIL:4,ENETRESET:39,EISCONN:30,ENOTCONN:53,ETOOMANYREFS:141,EUSERS:136,EDQUOT:19,ESTALE:72,ENOTSUP:138,ENOMEDIUM:148,EILSEQ:25,EOVERFLOW:61,ECANCELED:11,
ENOTRECOVERABLE:56,EOWNERDEAD:62,ESTRPIPE:135};function M(a){try{return a()}catch(b){if(!b.code)throw b;if("UNKNOWN"===b.code)throw new F.qa(28);throw new F.qa(eb[b.code]);}}function fb(a){return M(()=>{var b=fs.lstatSync(a).mode;O.Ta&&(b|=(b&292)>>2);return b})}function P(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.ua.Oa.root);b.reverse();return Ma(...b)}
var O={Ta:!1,lb(){O.Ta=!!process.platform.match(/^win/);var a=process.binding("constants").fs;O.qb={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,256:a.O_NOCTTY,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY,131072:a.O_NOFOLLOW}},ua(a){return O.createNode(null,"/",fb(a.Oa.root),0)},createNode(a,b,c){if(!K(c)&&!F.isFile(c)&&40960!==(c&61440))throw new F.qa(28);a=F.createNode(a,b,c);a.ra=O.ra;a.sa=O.sa;return a},va(a,b){a=M(a);O.Ta&&(a.blksize||(a.blksize=4096),a.blocks||(a.blocks=(a.size+
a.blksize-1)/a.blksize|0),a.mode|=(a.mode&292)>>2);return{dev:a.dev,ino:b.id,mode:a.mode,nlink:a.nlink,uid:a.uid,gid:a.gid,rdev:a.rdev,size:a.size,atime:a.atime,mtime:a.mtime,ctime:a.ctime,blksize:a.blksize,blocks:a.blocks}},wa(a,b,c,d,e,g,h){M(()=>{if(void 0!==c.mode){var k=c.mode;O.Ta&&(k&=384);d(a,k);b.mode=c.mode}if("number"===typeof(c.atime??c.mtime)){k=new Date(c.atime??h(a).atime);var m=new Date(c.mtime??h(a).mtime);e(a,k,m)}void 0!==c.size&&g(a,c.size)})},ra:{va(a){var b=P(a);return O.va(()=>
fs.lstatSync(b),a)},wa(a,b){var c=P(a);if(null!=b.mode&&b.Ya)throw new F.qa(52);O.wa(c,a,b,fs.chmodSync,fs.utimesSync,fs.truncateSync,fs.lstatSync)},lookup(a,b){var c=P(a);c=D(c+"/"+b);c=fb(c);return O.createNode(a,b,c)},Ca(a,b,c,d){var e=O.createNode(a,b,c,d),g=P(e);M(()=>{K(e.mode)?fs.mkdirSync(g,e.mode):fs.writeFileSync(g,"",{mode:e.mode})});return e},rename(a,b,c){var d=P(a),e=Na(P(b),c);try{F.unlink(e)}catch(g){}M(()=>fs.renameSync(d,e));a.name=c},unlink(a,b){var c=Na(P(a),b);M(()=>fs.unlinkSync(c))},
rmdir(a,b){var c=Na(P(a),b);M(()=>fs.rmdirSync(c))},readdir(a){var b=P(a);return M(()=>fs.readdirSync(b))},symlink(a,b,c){var d=Na(P(a),b);M(()=>fs.symlinkSync(c,d))},readlink(a){var b=P(a);return M(()=>fs.readlinkSync(b))},kb(a){var b=M(()=>fs.pc(a));b.Jb=b.Cb;return b}},sa:{va(a){return O.va(()=>fs.fstatSync(a.La),a.node)},wa(a,b){O.wa(a.La,a.node,b,fs.fchmodSync,fs.futimesSync,fs.ftruncateSync,fs.fstatSync)},open(a){var b=P(a.node);M(()=>{a.Ma.tb=1;var c=fs,d=c.openSync,e=a.flags;e&=-2721793;var g=
0,h;for(h in O.qb)e&h&&(g|=O.qb[h],e^=h);if(e)throw new F.qa(28);a.La=d.call(c,b,g)})},close(a){M(()=>{a.La&&0===--a.Ma.tb&&fs.closeSync(a.La)})},Fb(a){a.Ma.tb++},read(a,b,c,d,e){return M(()=>fs.readSync(a.La,b,c,d,e))},write(a,b,c,d,e){return M(()=>fs.writeSync(a.La,b,c,d,e))},xa(a,b,c){var d=b;1===c?d+=a.position:2===c&&F.isFile(a.node.mode)&&M(()=>{d+=fs.fstatSync(a.La).size});if(0>d)throw new F.qa(28);return d},Ja(a,b,c){if(!F.isFile(a.node.mode))throw new F.qa(43);x();O.sa.read(a,r,void 0,b,
c);return{za:void 0,Bb:!0}},Na(a,b,c,d){O.sa.write(a,b,0,d,c,!1);return 0}}},Q={Wa:16895,Pa:33279,ib:null,ua(a){function b(m){m=m.split("/");for(var l=d,n=0;n<m.length-1;n++){var q=m.slice(0,n+1).join("/");let y,A;(y=e)[A=q]||(y[A]=Q.createNode(l,m[n],Q.Wa,0));l=e[q]}return l}function c(m){m=m.split("/");return m[m.length-1]}ba||x();Q.ib??(Q.ib=new FileReaderSync);var d=Q.createNode(null,"/",Q.Wa,0),e={},g;for(g of a.Oa.files||[])Q.createNode(b(g.name),c(g.name),Q.Pa,0,g,g.lastModifiedDate);for(var h of a.Oa.blobs||
[])Q.createNode(b(h.name),c(h.name),Q.Pa,0,h.data);for(var k of a.Oa.packages||[])for(g of k.metadata.files)a=g.filename.slice(1),Q.createNode(b(a),c(a),Q.Pa,0,k.blob.slice(g.start,g.end));return d},createNode(a,b,c,d,e,g){d=F.createNode(a,b,c);d.mode=c;d.ra=Q.ra;d.sa=Q.sa;d.atime=d.mtime=d.ctime=(g||new Date).getTime();Q.Pa!==Q.Wa||x();c===Q.Pa?(d.size=e.size,d.ta=e):(d.size=4096,d.ta={});a&&(a.ta[b]=d);return d},ra:{va(a){return{dev:1,ino:a.id,mode:a.mode,nlink:1,uid:0,gid:0,rdev:0,size:a.size,
atime:new Date(a.atime),mtime:new Date(a.mtime),ctime:new Date(a.ctime),blksize:4096,blocks:Math.ceil(a.size/4096)}},wa(a,b){for(const c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c])},lookup(){throw new F.qa(44);},Ca(){throw new F.qa(63);},rename(){throw new F.qa(63);},unlink(){throw new F.qa(63);},rmdir(){throw new F.qa(63);},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.ta))b.push(c);return b},symlink(){throw new F.qa(63);}},sa:{read(a,b,c,d,e){if(e>=a.node.size)return 0;a=a.node.ta.slice(e,
e+d);d=Q.ib.readAsArrayBuffer(a);b.set(new Uint8Array(d),c);return a.size},write(){throw new F.qa(29);},xa(a,b,c){1===c?b+=a.position:2===c&&F.isFile(a.node.mode)&&(b+=a.node.size);if(0>b)throw new F.qa(28);return b}}},gb=async a=>{a=await ja(a);return new Uint8Array(a)},hb=0,ib=null,jb=[],kb=async(a,b)=>{"undefined"!=typeof Browser&&Browser.Qa();for(var c of jb)if(c.canHandle(b))return c.handle(a,b);return a},mb=async(a,b,c,d,e,g,h,k)=>{var m=b?Qa(D(a+"/"+b)):a;hb++;try{var l=c;"string"==typeof c&&
(l=await gb(c));l=await kb(l,m);k?.();if(!g){c=b;a&&(a="string"==typeof a?a:lb(a),c=b?D(a+"/"+b):a);var n=db(d,e),q=F.create(c,n);if(l){l=cb(l);F.chmod(q,n|146);var y=F.open(q,577);F.write(y,l,0,l.length,0,h);F.close(y);F.chmod(q,n)}}}finally{hb--,0==hb&&ib&&(b=ib,ib=null,b())}};function Ya(a,b){F.ob[a]={sa:b}}function K(a){return 16384===(a&61440)}
function L(a,b){var c=K(a.mode)?(c=R(a,"x"))?c:a.ra.lookup?0:2:54;if(c)throw new F.qa(c);for(c=F.Fa[nb(a.id,b)];c;c=c.Ka){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return F.lookup(a,b)}function bb(a){var b=nb(a.parent.id,a.name);if(F.Fa[b]===a)F.Fa[b]=a.Ka;else for(b=F.Fa[b];b;){if(b.Ka===a){b.Ka=a.Ka;break}b=b.Ka}}
function S(a,b={}){if(!a)throw new F.qa(44);b.Sa??(b.Sa=!0);"/"===a.charAt(0)||(a=F.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=F.root,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])if(e=La(e),F.cb(d)){a=e+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{e=D(e+"/"+a[g]);try{d=L(d,a[g])}catch(k){if(44===k?.ya&&h&&b.Rb)return{path:e};throw k;}!d.Da||h&&!b.Sa||(d=d.Da.root);if(40960===(d.mode&61440)&&(!h||
b.Ba)){if(!d.ra.readlink)throw new F.qa(52);d=d.ra.readlink(d);"/"===d.charAt(0)||(d=La(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new F.qa(32);}function lb(a){for(var b;;){if(F.cb(a))return a=a.ua.sb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function nb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%F.Fa.length}function ob(a){var b=nb(a.parent.id,a.name);a.Ka=F.Fa[b];F.Fa[b]=a}
function R(a,b){return F.$a?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function pb(a,b){if(!K(a.mode))return 54;try{return L(a,b),20}catch(c){}return R(a,"wx")}function qb(a,b,c){try{var d=L(a,b)}catch(e){return e.ya}if(a=R(a,"wx"))return a;if(c){if(!K(d.mode))return 54;if(F.cb(d)||lb(d)===F.cwd())return 10}else if(K(d.mode))return 31;return 0}function rb(a,b){if(!a)throw new F.qa(b);return a}
function U(a){a=F.Lb(a);if(!a)throw new F.qa(8);return a}function sb(a,b=-1){a=Object.assign(new F.zb,a);if(-1==b)a:{for(b=0;b<=F.Ab;b++)if(!F.streams[b])break a;throw new F.qa(33);}a.fd=b;return F.streams[b]=a}function tb(a,b=-1){a=sb(a,b);a.sa?.Fb?.(a);return a}function ub(a,b,c){var d=a?.sa.wa;a=d?a:b;d??=b.ra.wa;rb(d,63);d(a,c)}function vb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.Ra)}return b}
function wb(a){var b={Cb:4096,Jb:4096,blocks:1E6,Wb:5E5,Vb:5E5,files:F.fb,ec:F.fb-1,hc:42,flags:2,lc:255};a.ra.kb&&Object.assign(b,a.ra.kb(a.ua.Oa.root));return b}function xb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return F.Ca(a,b|8192,c)}function yb(a,b,c,d){ub(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),Ya:d})}function zb(a,b,c){if(K(b.mode))throw new F.qa(31);if(!F.isFile(b.mode))throw new F.qa(28);var d=R(b,"w");if(d)throw new F.qa(d);ub(a,b,{size:c,timestamp:Date.now()})}
function Ab(){F.mkdir("/dev");Ya(F.Ia(1,3),{read:()=>0,write:(d,e,g,h)=>h,xa:()=>0});xb("/dev/null",F.Ia(1,3));Xa(F.Ia(5,0),$a);Xa(F.Ia(6,0),ab);xb("/dev/tty",F.Ia(5,0));xb("/dev/tty1",F.Ia(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Pa(a),b=a.byteLength);return a[--b]};F.Ha("/dev","random",c);F.Ha("/dev","urandom",c);F.mkdir("/dev/shm");F.mkdir("/dev/shm/tmp")}
function Bb(){F.mkdir("/proc");var a=F.mkdir("/proc/self");F.mkdir("/proc/self/fd");F.ua({ua(){var b=F.createNode(a,"fd",16895,73);b.sa={xa:I.sa.xa};b.ra={lookup(c,d){c=+d;var e=U(c);c={parent:null,ua:{sb:"fake"},ra:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(F.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")}function Cb(a,b,c,d){a="string"==typeof a?a:lb(a);b=D(a+"/"+b);return F.create(b,db(c,d))}
function Db(a){if(!(a.Pb||a.Qb||a.link||a.ta))if(globalThis.XMLHttpRequest)x("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.ta=ka(a.url)}catch(b){throw new F.qa(29);}}
var F={root:null,Ra:[],ob:{},streams:[],fb:1,Fa:null,nb:"/",ab:!1,$a:!0,Ib:null,Va:0,qa:class{name="ErrnoError";constructor(a){this.ya=a}},zb:class{Ma={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.Ma.flags}set flags(a){this.Ma.flags=a}get position(){return this.Ma.position}set position(a){this.Ma.position=a}},yb:class{ra={};sa={};Da=null;constructor(a,b,c,d){a||=this;this.parent=a;this.ua=a.ua;this.id=F.fb++;this.name=b;this.mode=c;this.rdev=d;this.atime=
this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Qb(){return K(this.mode)}get Pb(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new F.yb(a,b,c,d);ob(a);return a},cb(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},Ab:4096,Lb:a=>F.streams[a],Db:{open(a){a.sa=
F.Kb(a.node.rdev).sa;a.sa.open?.(a)},xa(){throw new F.qa(70);}},eb:a=>a>>8,jc:a=>a&255,Ia:(a,b)=>a<<8|b,Kb:a=>F.ob[a],ub(a,b){function c(k){F.Va--;return b(k)}function d(k){if(k){if(!d.Hb)return d.Hb=!0,c(k)}else++g>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);F.Va++;1<F.Va&&p(`warning: ${F.Va} FS.syncfs operations in flight at once, probably just doing extra work`);var e=vb(F.root.ua),g=0,h;for(h of e)h.type.ub?h.type.ub(h,a,d):d(null)},ua(a,b,c){var d="/"===c;if(d&&F.root)throw new F.qa(10);
if(!d&&c){var e=S(c,{Sa:!1});c=e.path;e=e.node;if(e.Da)throw new F.qa(10);if(!K(e.mode))throw new F.qa(54);}b={type:a,Oa:b,sb:c,Ra:[]};a=a.ua(b);a.ua=b;b.root=a;d?F.root=a:e&&(e.Da=b,e.ua&&e.ua.Ra.push(b));return a},Tb(a){a=S(a,{Sa:!1});if(!a.node.Da)throw new F.qa(28);a=a.node;var b=a.Da,c=vb(b);for([,e]of Object.entries(F.Fa))for(;e;){var d=e.Ka;c.includes(e.ua)&&bb(e);var e=d}a.Da=null;a.ua.Ra.splice(a.ua.Ra.indexOf(b),1)},lookup(a,b){return a.ra.lookup(a,b)},Ca(a,b,c){var d=S(a,{parent:!0}).node;
a=E(a);if(!a)throw new F.qa(28);if("."===a||".."===a)throw new F.qa(20);var e=pb(d,a);if(e)throw new F.qa(e);if(!d.ra.Ca)throw new F.qa(63);return d.ra.Ca(d,a,b,c)},kb(a){return wb(S(a,{Ba:!0}).node)},oc(a){return wb(a.node)},create(a,b=438){return F.Ca(a,b&4095|32768,0)},mkdir(a,b=511){return F.Ca(a,b&1023|16384,0)},kc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{F.mkdir(d,b)}catch(g){if(20!=g.ya)throw g;}}},symlink(a,b){if(!Qa(a))throw new F.qa(44);var c=
S(b,{parent:!0}).node;if(!c)throw new F.qa(44);b=E(b);var d=pb(c,b);if(d)throw new F.qa(d);if(!c.ra.symlink)throw new F.qa(63);return c.ra.symlink(c,b,a)},rename(a,b){var c=La(a),d=La(b),e=E(a),g=E(b);var h=S(a,{parent:!0});var k=h.node;h=S(b,{parent:!0});h=h.node;if(!k||!h)throw new F.qa(44);if(k.ua!==h.ua)throw new F.qa(75);var m=L(k,e);a=Ra(a,d);if("."!==a.charAt(0))throw new F.qa(28);a=Ra(b,c);if("."!==a.charAt(0))throw new F.qa(55);try{var l=L(h,g)}catch(n){}if(m!==l){b=K(m.mode);if(e=qb(k,e,
b))throw new F.qa(e);if(e=l?qb(h,g,b):pb(h,g))throw new F.qa(e);if(!k.ra.rename)throw new F.qa(63);if(m.Da||l&&l.Da)throw new F.qa(10);if(h!==k&&(e=R(k,"w")))throw new F.qa(e);bb(m);try{k.ra.rename(m,h,g),m.parent=h}catch(n){throw n;}finally{ob(m)}}},rmdir(a){var b=S(a,{parent:!0}).node;a=E(a);var c=L(b,a),d=qb(b,a,!0);if(d)throw new F.qa(d);if(!b.ra.rmdir)throw new F.qa(63);if(c.Da)throw new F.qa(10);b.ra.rmdir(b,a);bb(c)},readdir(a){a=S(a,{Ba:!0}).node;return rb(a.ra.readdir,54)(a)},unlink(a){var b=
S(a,{parent:!0}).node;if(!b)throw new F.qa(44);a=E(a);var c=L(b,a),d=qb(b,a,!1);if(d)throw new F.qa(d);if(!b.ra.unlink)throw new F.qa(63);if(c.Da)throw new F.qa(10);b.ra.unlink(b,a);bb(c)},readlink(a){a=S(a).node;if(!a)throw new F.qa(44);if(!a.ra.readlink)throw new F.qa(28);return a.ra.readlink(a)},stat(a,b){a=S(a,{Ba:!b}).node;return rb(a.ra.va,63)(a)},fstat(a){var b=U(a);a=b.node;var c=b.sa.va;b=c?b:a;c??=a.ra.va;rb(c,63);return c(b)},lstat(a){return F.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?
S(a,{Ba:!c}).node:a;yb(null,a,b,c)},lchmod(a,b){F.chmod(a,b,!0)},fchmod(a,b){a=U(a);yb(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?S(a,{Ba:!d}).node:a;ub(null,a,{timestamp:Date.now(),Ya:d})},lchown(a,b,c){F.chown(a,b,c,!0)},fchown(a){a=U(a);ub(a,a.node,{timestamp:Date.now(),Ya:!1})},truncate(a,b){if(0>b)throw new F.qa(28);a="string"==typeof a?S(a,{Ba:!0}).node:a;zb(null,a,b)},ic(a,b){a=U(a);if(0>b||0===(a.flags&2097155))throw new F.qa(28);zb(a,a.node,b)},rc(a,b,c){a=S(a,{Ba:!0}).node;rb(a.ra.wa,
63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new F.qa(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");var g=S(a,{Ba:!(b&131072),Rb:!0});d=g.node;a=g.path}g=!1;if(b&64)if(d){if(b&128)throw new F.qa(20);}else{if(e)throw new F.qa(31);d=F.Ca(a,c|511,0);g=!0}if(!d)throw new F.qa(44);8192===(d.mode&61440)&&(b&=-513);
if(b&65536&&!K(d.mode))throw new F.qa(54);if(!g&&(d?40960===(d.mode&61440)?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=K(d.mode)&&("r"!==e||b&576)?31:R(d,e)):e=44,e))throw new F.qa(e);b&512&&!g&&F.truncate(d,0);b&=-131713;b=sb({node:d,path:lb(d),flags:b,seekable:!0,position:0,sa:d.sa,Sb:[],error:!1});b.sa.open&&b.sa.open(b);g&&F.chmod(d,c&511);return b},close(a){if(null===a.fd)throw new F.qa(8);a.Za&&(a.Za=null);try{a.sa.close&&a.sa.close(a)}catch(b){throw b;}finally{F.streams[a.fd]=null}a.fd=null},
xa(a,b,c){if(null===a.fd)throw new F.qa(8);if(!a.seekable||!a.sa.xa)throw new F.qa(70);if(0!=c&&1!=c&&2!=c)throw new F.qa(28);a.position=a.sa.xa(a,b,c);a.Sb=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new F.qa(28);if(null===a.fd)throw new F.qa(8);if(1===(a.flags&2097155))throw new F.qa(8);if(K(a.node.mode))throw new F.qa(31);if(!a.sa.read)throw new F.qa(28);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new F.qa(70);b=a.sa.read(a,b,c,d,e);g||(a.position+=b);return b},
write(a,b,c,d,e,g){if(0>d||0>e)throw new F.qa(28);if(null===a.fd)throw new F.qa(8);if(0===(a.flags&2097155))throw new F.qa(8);if(K(a.node.mode))throw new F.qa(31);if(!a.sa.write)throw new F.qa(28);a.seekable&&a.flags&1024&&F.xa(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new F.qa(70);b=a.sa.write(a,b,c,d,e,g);h||(a.position+=b);return b},Ja(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new F.qa(2);if(1===(a.flags&2097155))throw new F.qa(2);if(!a.sa.Ja)throw new F.qa(43);
if(!b)throw new F.qa(28);return a.sa.Ja(a,b,c,d,e)},Na(a,b,c,d,e){return a.sa.Na?a.sa.Na(a,b,c,d,e):0},bb(a,b,c){if(!a.sa.bb)throw new F.qa(59);return a.sa.bb(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&x(`Invalid encoding type "${b.encoding}"`);var c=F.open(a,b.flags);a=F.stat(a).size;var d=new Uint8Array(a);F.read(c,d,0,a,0);"utf8"===b.encoding&&(d=Sa(d));F.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=F.open(a,
c.flags,c.mode);b=cb(b);F.write(a,b,0,b.byteLength,void 0,c.bc);F.close(a)},cwd:()=>F.nb,chdir(a){a=S(a,{Ba:!0});if(null===a.node)throw new F.qa(44);if(!K(a.node.mode))throw new F.qa(54);var b=R(a.node,"x");if(b)throw new F.qa(b);F.nb=a.path},lb(){F.Fa=Array(4096);F.ua(I,{},"/");F.mkdir("/tmp");F.mkdir("/home");F.mkdir("/home/web_user");Ab();Bb();F.Ib={MEMFS:I,NODEFS:O,WORKERFS:Q}},Qa(a,b,c){F.ab=!0;a?F.Ha("/dev","stdin",a):F.symlink("/dev/tty","/dev/stdin");b?F.Ha("/dev","stdout",null,b):F.symlink("/dev/tty",
"/dev/stdout");c?F.Ha("/dev","stderr",null,c):F.symlink("/dev/tty1","/dev/stderr");F.open("/dev/stdin",0);F.open("/dev/stdout",1);F.open("/dev/stderr",1)},nc(){F.ab=!1;for(var a of F.streams)a&&F.close(a)},fc(a,b){try{var c=S(a,{Ba:!b});a=c.path}catch(g){}var d=!1,e=null;try{c=S(a,{parent:!0}),E(a),c=S(a,{Ba:!b}),d=!0,e=c.node}catch(g){}return d?e:null},cc(a,b){a="string"==typeof a?a:lb(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=D(a+"/"+c);try{F.mkdir(d)}catch(e){if(20!=
e.ya)throw e;}a=d}}return d},Ha(a,b,c,d){a=Na("string"==typeof a?a:lb(a),b);b=db(!!c,!!d);var e;(e=F.Ha).eb??(e.eb=64);e=F.Ia(F.Ha.eb++,0);Ya(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,k,m){for(var l=0,n=0;n<m;n++){try{var q=c()}catch(y){throw new F.qa(29);}if(void 0===q&&0===l)throw new F.qa(6);if(null===q||void 0===q)break;l++;h[k+n]=q}l&&(g.node.atime=Date.now());return l},write(g,h,k,m){for(var l=0;l<m;l++)try{d(h[k+l])}catch(n){throw new F.qa(29);}m&&(g.node.mtime=g.node.ctime=
Date.now());return l}});return xb(a,b,e)},Eb(a,b,c,d,e){class g{jb=!1;Ua=[];hb=void 0;wb=0;vb=0;get(l){if(!(l>this.length-1||0>l)){var n=l%this.chunkSize;return this.hb(l/this.chunkSize|0)[n]}}Ub(l){this.hb=l}xb(){var l=new XMLHttpRequest;l.open("HEAD",c,!1);l.send(null);200<=l.status&&300>l.status||304===l.status||x("Couldn't load "+c+". Status: "+l.status);var n=Number(l.getResponseHeader("Content-length")),q,y=(q=l.getResponseHeader("Accept-Ranges"))&&"bytes"===q;l=(q=l.getResponseHeader("Content-Encoding"))&&
"gzip"===q;var A=1048576;y||(A=n);var G=this;G.Ub(T=>{var Z=T*A,N=(T+1)*A-1;N=Math.min(N,n-1);if("undefined"==typeof G.Ua[T]){var Ub=G.Ua;Z>N&&x("invalid range ("+Z+", "+N+") or no bytes requested!");N>n-1&&x("only "+n+" bytes available! programmer error!");var J=new XMLHttpRequest;J.open("GET",c,!1);n!==A&&J.setRequestHeader("Range","bytes="+Z+"-"+N);J.responseType="arraybuffer";J.overrideMimeType&&J.overrideMimeType("text/plain; charset=x-user-defined");J.send(null);200<=J.status&&300>J.status||
304===J.status||x("Couldn't load "+c+". Status: "+J.status);Z=void 0!==J.response?new Uint8Array(J.response||[]):Va(J.responseText||"");Ub[T]=Z}"undefined"==typeof G.Ua[T]&&x("doXHR failed!");return G.Ua[T]});if(l||!n)A=n=1,A=n=this.hb(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.wb=n;this.vb=A;this.jb=!0}get length(){this.jb||this.xb();return this.wb}get chunkSize(){this.jb||this.xb();return this.vb}}if(globalThis.XMLHttpRequest){ba||x("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var h=new g;var k=void 0}else k=c,h=void 0;var m=Cb(a,b,d,e);h?m.ta=h:k&&(m.ta=null,m.url=k);Object.defineProperties(m,{Aa:{get:function(){return this.ta.length}}});a={};for(const [l,n]of Object.entries(m.sa))a[l]=(...q)=>{Db(m);return n(...q)};a.read=(l,n,q,y,A)=>{Db(m);l=l.node.ta;if(A>=l.length)n=0;else{y=Math.min(l.length-A,y);if(l.slice)for(var G=0;G<y;G++)n[q+G]=l[A+G];else for(G=0;G<y;G++)n[q+G]=l.get(A+G);n=y}return n};a.Ja=()=>{Db(m);x();throw new F.qa(48);};m.sa=a;return m}};
function Eb(a,b){if("/"===b.charAt(0))return b;a=-100===a?F.cwd():U(a).path;if(0==b.length)throw new F.qa(44);return a+"/"+b}
var Ja=void 0,Fb=[0,31,60,91,121,152,182,213,244,274,305,335],Gb=[0,31,59,90,120,151,181,212,243,273,304,334],Hb={},Ib=a=>{if(a instanceof za||"unwind"==a)return oa;fa(1,a)},Jb=a=>{oa=a;fa(a,new za(a))},Kb=a=>{if(!na)try{a()}catch(b){Ib(b)}finally{}},Lb={},Nb=()=>{if(!Mb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Lb)void 0===Lb[b]?delete a[b]:a[b]=Lb[b];var c=
[];for(b in a)c.push(`${b}=${a[b]}`);Mb=c}return Mb},Mb;F.dc=(a,b,c,d,e,g,h,k,m,l)=>{mb(a,b,c,d,e,k,m,l).then(g).catch(h)};F.mc=mb;F.lb();ca&&O.lb();f.callMain=Ob;f.ENV=Lb;f.FS=F;f.NODEFS=O;f.WORKERFS=Q;
var Pb,Qb,V,Ga,W,Rb,X,Sb,Tb,Ha,Vb,ua,Y,sc={l:(a,b,c,d)=>x(`Assertion failed: ${z(a)}, at: `+[b?z(b):"unknown filename",c,d?z(d):"unknown function"]),o:a=>{var b=new Fa(a);0==r[b.za+12]&&(r[b.za+12]=1,Ea--);r[b.za+13]=0;Da.push(b);return Vb(a)},q:()=>{V(0,0);var a=Da.pop();Sb(a.pb);B=0},e:()=>Ia([]),i:a=>Ia([a]),O:(a,b)=>Ia([a,b]),C:()=>{var a=Da.pop();a||x("no exception to throw");var b=a.pb;0==r[a.za+13]&&(Da.push(a),r[a.za+13]=1,r[a.za+12]=0,Ea++);Tb(b);B=b;throw B;},a:(a,b,c)=>{(new Fa(a)).Qa(b,
c);Tb(a);B=a;Ea++;throw B;},T:()=>Ea,f:a=>{B||=a;throw B;},y:function(a,b,c){Ja=c;try{var d=U(a);switch(b){case 0:var e=C();if(0>e)break;for(;F.streams[e];)e++;return tb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=C(),d.flags|=e,0;case 12:return e=C(),ra[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(g){if("undefined"==typeof F||"ErrnoError"!==g.name)throw g;return-g.ya}},E:function(a,b,c){Ja=c;try{var d=U(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;
if(d.tty.Ga.Mb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=C();u[e>>2]=25856;u[e+4>>2]=5;u[e+8>>2]=191;u[e+12>>2]=35387;for(var g=0;32>g;g++)r[e+g+17]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Ga.Nb)for(e=C(),a=[],g=0;32>g;g++)a.push(r[e+g+17]);return 0;case 21519:if(!d.tty)return-59;e=C();return u[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:return e=
C(),F.bb(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Ga.Ob&&(g=[24,80],e=C(),ra[e>>1]=g[0],ra[e+2>>1]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof F||"ErrnoError"!==h.name)throw h;return-h.ya}},F:function(a,b,c,d){Ja=d;try{b=z(b);b=Eb(a,b);var e=d?C():0;return F.open(b,c,e).fd}catch(g){if("undefined"==typeof F||"ErrnoError"!==g.name)throw g;return-g.ya}},X:function(a,b,c,d){try{return b=z(b),d=z(d),b=Eb(a,b),d=Eb(c,d),
F.rename(b,d),0}catch(e){if("undefined"==typeof F||"ErrnoError"!==e.name)throw e;return-e.ya}},W:function(a,b){try{a=z(a);var c=F.stat(a);v[b>>2]=c.dev;v[b+4>>2]=c.mode;v[b+8>>2]=c.nlink;v[b+12>>2]=c.uid;v[b+16>>2]=c.gid;v[b+20>>2]=c.rdev;w[b+24>>3]=BigInt(c.size);u[b+32>>2]=4096;u[b+36>>2]=c.blocks;var d=c.atime.getTime(),e=c.mtime.getTime(),g=c.ctime.getTime();w[b+40>>3]=BigInt(Math.floor(d/1E3));v[b+48>>2]=d%1E3*1E6;w[b+56>>3]=BigInt(Math.floor(e/1E3));v[b+64>>2]=e%1E3*1E6;w[b+72>>3]=BigInt(Math.floor(g/
1E3));v[b+80>>2]=g%1E3*1E6;w[b+88>>3]=BigInt(c.ino);return 0}catch(h){if("undefined"==typeof F||"ErrnoError"!==h.name)throw h;return-h.ya}},V:function(a,b,c){try{b=z(b);b=Eb(a,b);if(c)if(512===c)F.rmdir(b);else return-28;else F.unlink(b);return 0}catch(d){if("undefined"==typeof F||"ErrnoError"!==d.name)throw d;return-d.ya}},S:()=>x(""),Q:()=>{},M:()=>{throw Infinity;},Y:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);u[b>>2]=a.getSeconds();u[b+4>>2]=a.getMinutes();
u[b+8>>2]=a.getHours();u[b+12>>2]=a.getDate();u[b+16>>2]=a.getMonth();u[b+20>>2]=a.getFullYear()-1900;u[b+24>>2]=a.getDay();var c=a.getFullYear();u[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Gb:Fb)[a.getMonth()]+a.getDate()-1|0;u[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();u[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},R:(a,b)=>{Hb[a]&&(clearTimeout(Hb[a].id),delete Hb[a]);if(!b)return 0;
var c=setTimeout(()=>{delete Hb[a];Kb(()=>Qb(a,performance.now()))},b);Hb[a]={id:c,qc:b};return 0},J:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();v[a>>2]=60*Math.max(g,e);u[b>>2]=Number(g!=e);b=h=>{var k=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(k/60)).padStart(2,"0")}${String(k%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(H(a,t,c,17),H(b,t,d,17)):(H(a,t,d,17),H(b,t,c,17))},G:()=>Date.now(),U:a=>{var b=t.length;
a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ua.buffer.byteLength+65535)/65536|0;try{ua.grow(d);ta();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},_:(a,b)=>{var c=0,d=0,e;for(e of Nb()){var g=b+c;v[a+d>>2]=g;c+=H(e,t,g,Infinity)+1;d+=4}return 0},$:(a,b)=>{var c=Nb();v[a>>2]=c.length;a=0;for(var d of c)a+=Ua(d)+1;v[b>>2]=a;return 0},s:a=>{oa=a;Jb(a)},D:function(a){try{var b=
U(a);F.close(b);return 0}catch(c){if("undefined"==typeof F||"ErrnoError"!==c.name)throw c;return c.ya}},ba:function(a,b,c,d){try{a:{var e=U(a);a=b;for(var g,h=b=0;h<c;h++){var k=v[a>>2],m=v[a+4>>2];a+=8;var l=F.read(e,r,k,m,g);if(0>l){var n=-1;break a}b+=l;if(l<m)break;"undefined"!=typeof g&&(g+=l)}n=b}v[d>>2]=n;return 0}catch(q){if("undefined"==typeof F||"ErrnoError"!==q.name)throw q;return q.ya}},Z:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;
var e=U(a);F.xa(e,b,c);w[d>>3]=BigInt(e.position);e.Za&&0===b&&0===c&&(e.Za=null);return 0}catch(g){if("undefined"==typeof F||"ErrnoError"!==g.name)throw g;return g.ya}},aa:function(a,b,c,d){try{a:{var e=U(a);a=b;for(var g,h=b=0;h<c;h++){var k=v[a>>2],m=v[a+4>>2];a+=8;var l=F.write(e,r,k,m,g);if(0>l){var n=-1;break a}b+=l;if(l<m)break;"undefined"!=typeof g&&(g+=l)}n=b}v[d>>2]=n;return 0}catch(q){if("undefined"==typeof F||"ErrnoError"!==q.name)throw q;return q.ya}},c:Wb,d:Xb,k:Yb,m:Zb,L:$b,w:ac,r:bc,
I:cc,v:dc,z:ec,K:fc,j:gc,g:hc,b:ic,h:jc,n:kc,x:lc,p:mc,H:nc,u:oc,t:pc,B:qc,N:rc,A:a=>a,P:Jb};function Wb(a,b){var c=X();try{return Y.get(a)(b)}catch(d){W(c);if(d!==d+0)throw d;V(1,0)}}function Xb(a,b,c){var d=X();try{return Y.get(a)(b,c)}catch(e){W(d);if(e!==e+0)throw e;V(1,0)}}function hc(a,b){var c=X();try{Y.get(a)(b)}catch(d){W(c);if(d!==d+0)throw d;V(1,0)}}function lc(a,b,c,d,e,g){var h=X();try{Y.get(a)(b,c,d,e,g)}catch(k){W(h);if(k!==k+0)throw k;V(1,0)}}
function jc(a,b,c,d){var e=X();try{Y.get(a)(b,c,d)}catch(g){W(e);if(g!==g+0)throw g;V(1,0)}}function ic(a,b,c){var d=X();try{Y.get(a)(b,c)}catch(e){W(d);if(e!==e+0)throw e;V(1,0)}}function kc(a,b,c,d,e){var g=X();try{Y.get(a)(b,c,d,e)}catch(h){W(g);if(h!==h+0)throw h;V(1,0)}}function Yb(a,b,c,d){var e=X();try{return Y.get(a)(b,c,d)}catch(g){W(e);if(g!==g+0)throw g;V(1,0)}}function Zb(a,b,c,d,e){var g=X();try{return Y.get(a)(b,c,d,e)}catch(h){W(g);if(h!==h+0)throw h;V(1,0)}}
function rc(a,b,c,d,e,g){var h=X();try{Y.get(a)(b,c,d,e,g)}catch(k){W(h);if(k!==k+0)throw k;V(1,0)}}function qc(a,b,c,d){var e=X();try{Y.get(a)(b,c,d)}catch(g){W(e);if(g!==g+0)throw g;V(1,0)}}function gc(a){var b=X();try{Y.get(a)()}catch(c){W(b);if(c!==c+0)throw c;V(1,0)}}function bc(a,b,c,d,e,g,h){var k=X();try{return Y.get(a)(b,c,d,e,g,h)}catch(m){W(k);if(m!==m+0)throw m;V(1,0)}}function ac(a,b,c,d,e,g){var h=X();try{return Y.get(a)(b,c,d,e,g)}catch(k){W(h);if(k!==k+0)throw k;V(1,0)}}
function ec(a,b,c,d,e,g){var h=X();try{return Y.get(a)(b,c,d,e,g)}catch(k){W(h);if(k!==k+0)throw k;V(1,0)}}function $b(a,b,c,d,e,g){var h=X();try{return Y.get(a)(b,c,d,e,g)}catch(k){W(h);if(k!==k+0)throw k;V(1,0)}}function fc(a,b,c){var d=X();try{return Y.get(a)(b,c)}catch(e){W(d);if(e!==e+0)throw e;V(1,0)}}function cc(a,b,c,d,e,g,h,k){var m=X();try{return Y.get(a)(b,c,d,e,g,h,k)}catch(l){W(m);if(l!==l+0)throw l;V(1,0)}}
function mc(a,b,c,d,e,g,h,k){var m=X();try{Y.get(a)(b,c,d,e,g,h,k)}catch(l){W(m);if(l!==l+0)throw l;V(1,0)}}function dc(a,b,c,d,e,g,h,k,m,l,n,q){var y=X();try{return Y.get(a)(b,c,d,e,g,h,k,m,l,n,q)}catch(A){W(y);if(A!==A+0)throw A;V(1,0)}}function nc(a,b,c,d,e,g,h,k,m){var l=X();try{Y.get(a)(b,c,d,e,g,h,k,m)}catch(n){W(l);if(n!==n+0)throw n;V(1,0)}}function oc(a,b,c,d,e,g,h,k,m,l,n){var q=X();try{Y.get(a)(b,c,d,e,g,h,k,m,l,n)}catch(y){W(q);if(y!==y+0)throw y;V(1,0)}}
function pc(a,b,c,d,e,g,h,k,m,l,n,q,y,A,G,T){var Z=X();try{Y.get(a)(b,c,d,e,g,h,k,m,l,n,q,y,A,G,T)}catch(N){W(Z);if(N!==N+0)throw N;V(1,0)}}function Ob(a=[]){var b=Pb;a.unshift(ea);var c=a.length,d=Rb(4*(c+1)),e=d,g;for(g of a){a=v;var h=e>>2,k=g,m=Ua(k)+1,l=Rb(m);H(k,t,l,m);a[h]=l;e+=4}v[e>>2]=0;try{var n=b(c,d);oa=n;Jb(n);return n}catch(q){return Ib(q)}}
function tc(a=da){if(0<hb)ib=tc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;){var b=f.preRun.shift();Aa.push(b)}for(;0<Aa.length;)Aa.shift()(f);0<hb?ib=tc:(f.calledRun=!0,na||(sa=!0,f.noFSInit||F.ab||F.Qa(),uc.da(),F.$a=!1,pa?.(f),f.noInitialRun||Ob(a)))}}var uc;
uc=await (async function(){var a={a:sc};va??=f.locateFile?f.locateFile?f.locateFile("qpdf.wasm",ia):ia+"qpdf.wasm":(new URL("qpdf.wasm",import.meta.url)).href;a=uc=(await ya(a)).instance.exports;Pb=f._main=a.ea;Qb=a.ga;V=a.ha;Ga=a.ia;W=a.ja;Rb=a.ka;X=a.la;Sb=a.ma;Tb=a.na;Ha=a.oa;Vb=a.pa;ua=a.ca;Y=a.fa;ta();return uc}());tc();
Object.assign(F,{init:F.Qa,mkdir:F.mkdir,mount:F.ua,unlink:F.unlink,unmount:F.Tb,chdir:F.chdir,stat:F.stat,rmdir:F.rmdir,writeFile:F.writeFile,readFile:F.readFile,createLazyFile:F.Eb,setIgnorePermissions:function(a){F.$a=a}});sa?moduleRtn=f:moduleRtn=new Promise((a,b)=>{pa=a;qa=b});
;return moduleRtn}export default Module;
