async function Module(moduleArg={}){var moduleRtn;var f=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(ca){const {createRequire:a}=await import("module");var require=a(import.meta.url)}f.noInitialRun=!0;var da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=import.meta.url,ia="",ja,ka;
if(ca){var fs=require("fs");ha.startsWith("file:")&&(ia=require("path").dirname(require("url").fileURLToPath(ha))+"/");ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";
b.send(null);return new Uint8Array(b.response)});ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}
var ma=console.log.bind(console),p=console.error.bind(console),na=!1,oa,la=a=>a.startsWith("file://"),pa,qa,r,u,ra,v,x,y,sa=!1;function ta(){var a=ua.buffer;r=new Int8Array(a);ra=new Int16Array(a);u=new Uint8Array(a);new Uint16Array(a);v=new Int32Array(a);x=new Uint32Array(a);new Float32Array(a);new Float64Array(a);y=new BigInt64Array(a);new BigUint64Array(a)}function z(a){a="Aborted("+a+")";p(a);na=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");qa?.(a);throw a;}var va;
async function wa(a){try{var b=await ja(a);return new Uint8Array(b)}catch{}if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function xa(a,b){try{var c=await wa(a);return await WebAssembly.instantiate(c,b)}catch(d){p(`failed to asynchronously prepare wasm: ${d}`),z(d)}}
async function ya(a){var b=va;if(!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){p(`wasm streaming compile failed: ${d}`),p("falling back to ArrayBuffer instantiation")}return xa(b,a)}class za{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Aa=[],Ba=new TextDecoder,Ca=(a,b)=>{for(var c=b+void 0;a[b]&&!(b>=c);)++b;return b},A=a=>a?Ba.decode(u.subarray(a,Ca(u,a))):"",Da=[],Ea=0,B=0;class Fa{constructor(a){this.nb=a;this.ya=a-24}Oa(a,b){x[this.ya+16>>2]=0;x[this.ya+4>>2]=a;x[this.ya+8>>2]=b}}
var Ia=a=>{var b=B;if(!b)return Ga(0),0;var c=new Fa(b);x[c.ya+16>>2]=b;var d=x[c.ya+4>>2];if(!d)return Ga(0),b;for(var e of a){if(0===e||e===d)break;if(Ha(e,d,c.ya+16))return Ga(e),b}Ga(d);return b},C=()=>{var a=v[+Ja>>2];Ja+=4;return a},Ka=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},D=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ka(a.split("/").filter(d=>!!d),!b).join("/"))||
b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},La=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},F=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Ma=(...a)=>D(a.join("/")),Na=(a,b)=>D(a+"/"+b),Oa=()=>{if(ca){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>crypto.getRandomValues(b)},Pa=a=>{(Pa=Oa())(a)},Qa=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:G.cwd();if("string"!=
typeof c)throw new TypeError("Arguments to path.resolve must be strings");if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ka(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},Ra=(a,b)=>{function c(h){for(var l=0;l<h.length&&""===h[l];l++);for(var m=h.length-1;0<=m&&""===h[m];m--);return l>m?[]:h.slice(l,m-l+1)}a=Qa(a).slice(1);b=Qa(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,g=0;g<d;g++)if(a[g]!==b[g]){e=g;break}d=[];for(g=e;g<a.length;g++)d.push("..");
d=d.concat(b.slice(e));return d.join("/")},Sa=a=>{var b=Ca(a,0);return Ba.decode(a.buffer?a.subarray(0,b):new Uint8Array(a.slice(0,b)))},Ta=[],Ua=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},H=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.codePointAt(g);if(127>=h){if(c>=d)break;b[c++]=h}else if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6;b[c++]=128|h&63}else if(65535>=h){if(c+2>=d)break;
b[c++]=224|h>>12;b[c++]=128|h>>6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63;b[c++]=128|h>>6&63;b[c++]=128|h&63;g++}}b[c]=0;return c-e},Va=a=>{var b=Array(Ua(a)+1);a=H(a,b,0,b.length);b.length=a;return b},Wa=[];function Xa(a,b){Wa[a]={input:[],output:[],Ea:b};Ya(a,Za)}
var Za={open(a){var b=Wa[a.node.rdev];if(!b)throw new G.oa(43);a.tty=b;a.seekable=!1},close(a){a.tty.Ea.fsync(a.tty)},fsync(a){a.tty.Ea.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.Ea.pb)throw new G.oa(60);for(var e=0,g=0;g<d;g++){try{var h=a.tty.Ea.pb(a.tty)}catch(l){throw new G.oa(29);}if(void 0===h&&0===e)throw new G.oa(6);if(null===h||void 0===h)break;e++;b[c+g]=h}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.Ea.fb)throw new G.oa(60);try{for(var e=0;e<d;e++)a.tty.Ea.fb(a.tty,
b[c+e])}catch(g){throw new G.oa(29);}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},$a={pb(){a:{if(!Ta.length){var a=null;if(ca){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}0<c&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}Ta=Va(a)}a=Ta.shift()}return a},fb(a,b){null===b||10===b?(ma(Sa(a.output)),a.output=[]):
0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(ma(Sa(a.output)),a.output=[])},Jb(){return{Wb:25856,Yb:5,Vb:191,Xb:35387,Ub:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Kb(){return 0},Lb(){return[24,80]}},ab={fb(a,b){null===b||10===b?(p(Sa(a.output)),a.output=[]):0!=b&&a.output.push(b)},fsync(a){0<a.output?.length&&(p(Sa(a.output)),a.output=[])}},I={Ca:null,sa(){return I.createNode(null,"/",16895,0)},createNode(a,b,c,d){if(24576===(c&61440)||G.isFIFO(c))throw new G.oa(63);
I.Ca||(I.Ca={dir:{node:{ua:I.pa.ua,va:I.pa.va,lookup:I.pa.lookup,Aa:I.pa.Aa,rename:I.pa.rename,unlink:I.pa.unlink,rmdir:I.pa.rmdir,readdir:I.pa.readdir,symlink:I.pa.symlink},stream:{wa:I.qa.wa}},file:{node:{ua:I.pa.ua,va:I.pa.va},stream:{wa:I.qa.wa,read:I.qa.read,write:I.qa.write,Ha:I.qa.Ha,La:I.qa.La}},link:{node:{ua:I.pa.ua,va:I.pa.va,readlink:I.pa.readlink},stream:{}},kb:{node:{ua:I.pa.ua,va:I.pa.va},stream:G.Bb}});c=G.createNode(a,b,c,d);K(c.mode)?(c.pa=I.Ca.dir.node,c.qa=I.Ca.dir.stream,c.ra=
{}):G.isFile(c.mode)?(c.pa=I.Ca.file.node,c.qa=I.Ca.file.stream,c.ta=0,c.ra=null):40960===(c.mode&61440)?(c.pa=I.Ca.link.node,c.qa=I.Ca.link.stream):8192===(c.mode&61440)&&(c.pa=I.Ca.kb.node,c.qa=I.Ca.kb.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.ra[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},fc(a){return a.ra?a.ra.subarray?a.ra.subarray(0,a.ta):new Uint8Array(a.ra):new Uint8Array(0)},pa:{ua(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=
0;b.rdev=a.rdev;K(a.mode)?b.size=4096:G.isFile(a.mode)?b.size=a.ta:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},va(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c]);void 0!==b.size&&(b=b.size,a.ta!=b&&(0==b?(a.ra=null,a.ta=0):(c=a.ra,a.ra=new Uint8Array(b),c&&a.ra.set(c.subarray(0,Math.min(b,a.ta))),a.ta=b)))},lookup(){I.Va||(I.Va=
new G.oa(44),I.Va.stack="<generic error, no stack>");throw I.Va;},Aa(a,b,c,d){return I.createNode(a,b,c,d)},rename(a,b,c){try{var d=L(b,c)}catch(g){}if(d){if(K(a.mode))for(var e in d.ra)throw new G.oa(55);bb(d)}delete a.parent.ra[a.name];b.ra[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.ra[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=L(a,b),d;for(d in c.ra)throw new G.oa(55);delete a.ra[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".","..",...Object.keys(a.ra)]},
symlink(a,b,c){a=I.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(40960!==(a.mode&61440))throw new G.oa(28);return a.link}},qa:{read(a,b,c,d,e){var g=a.node.ra;if(e>=a.node.ta)return 0;a=Math.min(a.node.ta-e,d);if(8<a&&g.subarray)b.set(g.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=g[e+d];return a},write(a,b,c,d,e,g){b.buffer===r.buffer&&(g=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(b.subarray&&(!a.ra||a.ra.subarray)){if(g)return a.ra=b.subarray(c,c+d),a.ta=d;if(0===a.ta&&
0===e)return a.ra=b.slice(c,c+d),a.ta=d;if(e+d<=a.ta)return a.ra.set(b.subarray(c,c+d),e),d}g=e+d;var h=a.ra?a.ra.length:0;h>=g||(g=Math.max(g,h*(1048576>h?2:1.125)>>>0),0!=h&&(g=Math.max(g,256)),h=a.ra,a.ra=new Uint8Array(g),0<a.ta&&a.ra.set(h.subarray(0,a.ta),0));if(a.ra.subarray&&b.subarray)a.ra.set(b.subarray(c,c+d),e);else for(g=0;g<d;g++)a.ra[e+g]=b[c+g];a.ta=Math.max(a.ta,e+d);return d},wa(a,b,c){1===c?b+=a.position:2===c&&G.isFile(a.node.mode)&&(b+=a.node.ta);if(0>b)throw new G.oa(28);return b},
Ha(a,b,c,d,e){if(!G.isFile(a.node.mode))throw new G.oa(43);a=a.node.ra;if(e&2||!a||a.buffer!==r.buffer){d=!0;z();e=void 0;if(!e)throw new G.oa(48);if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);r.set(a,e)}}else d=!1,e=a.byteOffset;return{ya:e,zb:d}},La(a,b,c,d){I.qa.write(a,b,0,d,c,!1);return 0}}},cb=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},db={EPERM:63,ENOENT:44,ESRCH:71,EINTR:27,EIO:29,ENXIO:60,E2BIG:1,ENOEXEC:45,EBADF:8,ECHILD:12,EAGAIN:6,
EWOULDBLOCK:6,ENOMEM:48,EACCES:2,EFAULT:21,ENOTBLK:105,EBUSY:10,EEXIST:20,EXDEV:75,ENODEV:43,ENOTDIR:54,EISDIR:31,EINVAL:28,ENFILE:41,EMFILE:33,ENOTTY:59,ETXTBSY:74,EFBIG:22,ENOSPC:51,ESPIPE:70,EROFS:69,EMLINK:34,EPIPE:64,EDOM:18,ERANGE:68,ENOMSG:49,EIDRM:24,ECHRNG:106,EL2NSYNC:156,EL3HLT:107,EL3RST:108,ELNRNG:109,EUNATCH:110,ENOCSI:111,EL2HLT:112,EDEADLK:16,ENOLCK:46,EBADE:113,EBADR:114,EXFULL:115,ENOANO:104,EBADRQC:103,EBADSLT:102,EDEADLOCK:16,EBFONT:101,ENOSTR:100,ENODATA:116,ETIME:117,ENOSR:118,
ENONET:119,ENOPKG:120,EREMOTE:121,ENOLINK:47,EADV:122,ESRMNT:123,ECOMM:124,EPROTO:65,EMULTIHOP:36,EDOTDOT:125,EBADMSG:9,ENOTUNIQ:126,EBADFD:127,EREMCHG:128,ELIBACC:129,ELIBBAD:130,ELIBSCN:131,ELIBMAX:132,ELIBEXEC:133,ENOSYS:52,ENOTEMPTY:55,ENAMETOOLONG:37,ELOOP:32,EOPNOTSUPP:138,EPFNOSUPPORT:139,ECONNRESET:15,ENOBUFS:42,EAFNOSUPPORT:5,EPROTOTYPE:67,ENOTSOCK:57,ENOPROTOOPT:50,ESHUTDOWN:140,ECONNREFUSED:14,EADDRINUSE:3,ECONNABORTED:13,ENETUNREACH:40,ENETDOWN:38,ETIMEDOUT:73,EHOSTDOWN:142,EHOSTUNREACH:23,
EINPROGRESS:26,EALREADY:7,EDESTADDRREQ:17,EMSGSIZE:35,EPROTONOSUPPORT:66,ESOCKTNOSUPPORT:137,EADDRNOTAVAIL:4,ENETRESET:39,EISCONN:30,ENOTCONN:53,ETOOMANYREFS:141,EUSERS:136,EDQUOT:19,ESTALE:72,ENOTSUP:138,ENOMEDIUM:148,EILSEQ:25,EOVERFLOW:61,ECANCELED:11,ENOTRECOVERABLE:56,EOWNERDEAD:62,ESTRPIPE:135};function M(a){try{return a()}catch(b){if(!b.code)throw b;if("UNKNOWN"===b.code)throw new G.oa(28);throw new G.oa(db[b.code]);}}
function eb(a){return M(()=>{var b=fs.lstatSync(a).mode;O.Ra&&(b|=(b&292)>>2);return b})}function P(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.sa.Ma.root);b.reverse();return Ma(...b)}
var O={Ra:!1,jb(){O.Ra=!!process.platform.match(/^win/);var a=process.binding("constants").fs;O.ob={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,256:a.O_NOCTTY,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY,131072:a.O_NOFOLLOW}},sa(a){return O.createNode(null,"/",eb(a.Ma.root),0)},createNode(a,b,c){if(!K(c)&&!G.isFile(c)&&40960!==(c&61440))throw new G.oa(28);a=G.createNode(a,b,c);a.pa=O.pa;a.qa=O.qa;return a},ua(a,b){a=M(a);O.Ra&&(a.blksize||(a.blksize=4096),a.blocks||(a.blocks=(a.size+
a.blksize-1)/a.blksize|0),a.mode|=(a.mode&292)>>2);return{dev:a.dev,ino:b.id,mode:a.mode,nlink:a.nlink,uid:a.uid,gid:a.gid,rdev:a.rdev,size:a.size,atime:a.atime,mtime:a.mtime,ctime:a.ctime,blksize:a.blksize,blocks:a.blocks}},va(a,b,c,d,e,g,h){M(()=>{if(void 0!==c.mode){var l=c.mode;O.Ra&&(l&=384);d(a,l);b.mode=c.mode}if("number"===typeof(c.atime??c.mtime)){l=new Date(c.atime??h(a).atime);var m=new Date(c.mtime??h(a).mtime);e(a,l,m)}void 0!==c.size&&g(a,c.size)})},pa:{ua(a){var b=P(a);return O.ua(()=>
fs.lstatSync(b),a)},va(a,b){var c=P(a);if(null!=b.mode&&b.Wa)throw new G.oa(52);O.va(c,a,b,fs.chmodSync,fs.utimesSync,fs.truncateSync,fs.lstatSync)},lookup(a,b){var c=P(a);c=D(c+"/"+b);c=eb(c);return O.createNode(a,b,c)},Aa(a,b,c,d){var e=O.createNode(a,b,c,d),g=P(e);M(()=>{K(e.mode)?fs.mkdirSync(g,e.mode):fs.writeFileSync(g,"",{mode:e.mode})});return e},rename(a,b,c){var d=P(a),e=Na(P(b),c);try{G.unlink(e)}catch(g){}M(()=>fs.renameSync(d,e));a.name=c},unlink(a,b){var c=Na(P(a),b);M(()=>fs.unlinkSync(c))},
rmdir(a,b){var c=Na(P(a),b);M(()=>fs.rmdirSync(c))},readdir(a){var b=P(a);return M(()=>fs.readdirSync(b))},symlink(a,b,c){var d=Na(P(a),b);M(()=>fs.symlinkSync(c,d))},readlink(a){var b=P(a);return M(()=>fs.readlinkSync(b))},ib(a){var b=M(()=>fs.nc(a));b.Gb=b.Ab;return b}},qa:{ua(a){return O.ua(()=>fs.fstatSync(a.Ja),a.node)},va(a,b){O.va(a.Ja,a.node,b,fs.fchmodSync,fs.futimesSync,fs.ftruncateSync,fs.fstatSync)},open(a){var b=P(a.node);M(()=>{a.Ka.sb=1;var c=fs,d=c.openSync,e=a.flags;e&=-2721793;var g=
0,h;for(h in O.ob)e&h&&(g|=O.ob[h],e^=h);if(e)throw new G.oa(28);a.Ja=d.call(c,b,g)})},close(a){M(()=>{a.Ja&&0===--a.Ka.sb&&fs.closeSync(a.Ja)})},Db(a){a.Ka.sb++},read(a,b,c,d,e){return M(()=>fs.readSync(a.Ja,new Int8Array(b.buffer,c,d),0,d,e))},write(a,b,c,d,e){return M(()=>fs.writeSync(a.Ja,new Int8Array(b.buffer,c,d),0,d,e))},wa(a,b,c){var d=b;1===c?d+=a.position:2===c&&G.isFile(a.node.mode)&&M(()=>{d+=fs.fstatSync(a.Ja).size});if(0>d)throw new G.oa(28);return d},Ha(a,b,c){if(!G.isFile(a.node.mode))throw new G.oa(43);
z();O.qa.read(a,r,void 0,b,c);return{ya:void 0,zb:!0}},La(a,b,c,d){O.qa.write(a,b,0,d,c,!1);return 0}}},Q={Ua:16895,Na:33279,hb:null,sa(a){function b(m){m=m.split("/");for(var k=d,n=0;n<m.length-1;n++){var q=m.slice(0,n+1).join("/");let w,t;(w=e)[t=q]||(w[t]=Q.createNode(k,m[n],Q.Ua,0));k=e[q]}return k}function c(m){m=m.split("/");return m[m.length-1]}ba||z();Q.hb??(Q.hb=new FileReaderSync);var d=Q.createNode(null,"/",Q.Ua,0),e={},g;for(g of a.Ma.files||[])Q.createNode(b(g.name),c(g.name),Q.Na,0,
g,g.lastModifiedDate);for(var h of a.Ma.blobs||[])Q.createNode(b(h.name),c(h.name),Q.Na,0,h.data);for(var l of a.Ma.packages||[])for(g of l.metadata.files)a=g.filename.slice(1),Q.createNode(b(a),c(a),Q.Na,0,l.blob.slice(g.start,g.end));return d},createNode(a,b,c,d,e,g){d=G.createNode(a,b,c);d.mode=c;d.pa=Q.pa;d.qa=Q.qa;d.atime=d.mtime=d.ctime=(g||new Date).getTime();Q.Na!==Q.Ua||z();c===Q.Na?(d.size=e.size,d.ra=e):(d.size=4096,d.ra={});a&&(a.ra[b]=d);return d},pa:{ua(a){return{dev:1,ino:a.id,mode:a.mode,
nlink:1,uid:0,gid:0,rdev:0,size:a.size,atime:new Date(a.atime),mtime:new Date(a.mtime),ctime:new Date(a.ctime),blksize:4096,blocks:Math.ceil(a.size/4096)}},va(a,b){for(const c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=b[c])},lookup(){throw new G.oa(44);},Aa(){throw new G.oa(63);},rename(){throw new G.oa(63);},unlink(){throw new G.oa(63);},rmdir(){throw new G.oa(63);},readdir(a){var b=[".",".."],c;for(c of Object.keys(a.ra))b.push(c);return b},symlink(){throw new G.oa(63);}},qa:{read(a,
b,c,d,e){if(e>=a.node.size)return 0;a=a.node.ra.slice(e,e+d);d=Q.hb.readAsArrayBuffer(a);b.set(new Uint8Array(d),c);return a.size},write(){throw new G.oa(29);},wa(a,b,c){1===c?b+=a.position:2===c&&G.isFile(a.node.mode)&&(b+=a.node.size);if(0>b)throw new G.oa(28);return b}}},fb=async a=>{a=await ja(a);return new Uint8Array(a)},gb=0,hb=null,ib=[],jb=async(a,b)=>{"undefined"!=typeof Browser&&Browser.Oa();for(var c of ib)if(c.canHandle(b))return c.handle(a,b);return a},lb=async(a,b,c,d,e,g,h,l)=>{var m=
b?Qa(D(a+"/"+b)):a;gb++;try{var k=c;"string"==typeof c&&(k=await fb(c));k=await jb(k,m);l?.();if(!g){c=b;a&&(a="string"==typeof a?a:kb(a),c=b?D(a+"/"+b):a);var n=cb(d,e),q=G.create(c,n);if(k){if("string"==typeof k){var w=Array(k.length);b=0;for(var t=k.length;b<t;++b)w[b]=k.charCodeAt(b);k=w}G.chmod(q,n|146);var E=G.open(q,577);G.write(E,k,0,k.length,0,h);G.close(E);G.chmod(q,n)}}}finally{gb--,0==gb&&hb&&(h=hb,hb=null,h())}};function Ya(a,b){G.mb[a]={qa:b}}function K(a){return 16384===(a&61440)}
function L(a,b){var c=K(a.mode)?(c=R(a,"x"))?c:a.pa.lookup?0:2:54;if(c)throw new G.oa(c);for(c=G.Da[mb(a.id,b)];c;c=c.Ia){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return G.lookup(a,b)}function bb(a){var b=mb(a.parent.id,a.name);if(G.Da[b]===a)G.Da[b]=a.Ia;else for(b=G.Da[b];b;){if(b.Ia===a){b.Ia=a.Ia;break}b=b.Ia}}
function S(a,b={}){if(!a)throw new G.oa(44);b.Qa??(b.Qa=!0);"/"===a.charAt(0)||(a=G.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(l=>!!l);for(var d=G.root,e="/",g=0;g<a.length;g++){var h=g===a.length-1;if(h&&b.parent)break;if("."!==a[g])if(".."===a[g])if(e=La(e),G.ab(d)){a=e+"/"+a.slice(g+1).join("/");c--;continue a}else d=d.parent;else{e=D(e+"/"+a[g]);try{d=L(d,a[g])}catch(l){if(44===l?.xa&&h&&b.Ob)return{path:e};throw l;}!d.Ba||h&&!b.Qa||(d=d.Ba.root);if(40960===(d.mode&61440)&&(!h||
b.za)){if(!d.pa.readlink)throw new G.oa(52);d=d.pa.readlink(d);"/"===d.charAt(0)||(d=La(e)+"/"+d);a=d+"/"+a.slice(g+1).join("/");continue a}}}return{path:e,node:d}}throw new G.oa(32);}function kb(a){for(var b;;){if(G.ab(a))return a=a.sa.qb,b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}}function mb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%G.Da.length}function nb(a){var b=mb(a.parent.id,a.name);a.Ia=G.Da[b];G.Da[b]=a}
function ob(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function R(a,b){if(G.Ya)return 0;if(!b.includes("r")||a.mode&292){if(b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73))return 2}else return 2;return 0}function pb(a,b){if(!K(a.mode))return 54;try{return L(a,b),20}catch(c){}return R(a,"wx")}
function qb(a,b,c){try{var d=L(a,b)}catch(e){return e.xa}if(a=R(a,"wx"))return a;if(c){if(!K(d.mode))return 54;if(G.ab(d)||kb(d)===G.cwd())return 10}else if(K(d.mode))return 31;return 0}function rb(a,b){if(!a)throw new G.oa(b);return a}function U(a){a=G.Ib(a);if(!a)throw new G.oa(8);return a}function sb(a,b=-1){a=Object.assign(new G.xb,a);if(-1==b)a:{for(b=0;b<=G.yb;b++)if(!G.streams[b])break a;throw new G.oa(33);}a.fd=b;return G.streams[b]=a}function tb(a,b=-1){a=sb(a,b);a.qa?.Db?.(a);return a}
function ub(a,b,c){var d=a?.qa.va;a=d?a:b;d??=b.pa.va;rb(d,63);d(a,c)}function vb(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.Pa)}return b}function wb(a){var b={Ab:4096,Gb:4096,blocks:1E6,Tb:5E5,Sb:5E5,files:G.cb,bc:G.cb-1,dc:42,flags:2,jc:255};a.pa.ib&&Object.assign(b,a.pa.ib(a.sa.Ma.root));return b}function xb(a,b,c){"undefined"==typeof c&&(c=b,b=438);return G.Aa(a,b|8192,c)}function yb(a,b,c,d){ub(a,b,{mode:c&4095|b.mode&-4096,ctime:Date.now(),Wa:d})}
function zb(a,b,c){if(K(b.mode))throw new G.oa(31);if(!G.isFile(b.mode))throw new G.oa(28);var d=R(b,"w");if(d)throw new G.oa(d);ub(a,b,{size:c,timestamp:Date.now()})}
function Ab(){G.mkdir("/dev");Ya(G.Ga(1,3),{read:()=>0,write:(d,e,g,h)=>h,wa:()=>0});xb("/dev/null",G.Ga(1,3));Xa(G.Ga(5,0),$a);Xa(G.Ga(6,0),ab);xb("/dev/tty",G.Ga(5,0));xb("/dev/tty1",G.Ga(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Pa(a),b=a.byteLength);return a[--b]};G.Fa("/dev","random",c);G.Fa("/dev","urandom",c);G.mkdir("/dev/shm");G.mkdir("/dev/shm/tmp")}
function Bb(){G.mkdir("/proc");var a=G.mkdir("/proc/self");G.mkdir("/proc/self/fd");G.sa({sa(){var b=G.createNode(a,"fd",16895,73);b.qa={wa:I.qa.wa};b.pa={lookup(c,d){c=+d;var e=U(c);c={parent:null,sa:{qb:"fake"},pa:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(G.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")}function Cb(a,b,c,d){a="string"==typeof a?a:kb(a);b=D(a+"/"+b);return G.create(b,cb(c,d))}
function Db(a){if(!(a.Mb||a.Nb||a.link||a.ra))if(globalThis.XMLHttpRequest)z("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.ra=ka(a.url)}catch(b){throw new G.oa(29);}}
var G={root:null,Pa:[],mb:{},streams:[],cb:1,Da:null,lb:"/",Za:!1,Ya:!0,Fb:null,Ta:0,oa:class{name="ErrnoError";constructor(a){this.xa=a}},xb:class{Ka={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.Ka.flags}set flags(a){this.Ka.flags=a}get position(){return this.Ka.position}set position(a){this.Ka.position=a}},wb:class{pa={};qa={};Ba=null;constructor(a,b,c,d){a||=this;this.parent=a;this.sa=a.sa;this.id=G.cb++;this.name=b;this.mode=c;this.rdev=d;this.atime=
this.mtime=this.ctime=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Nb(){return K(this.mode)}get Mb(){return 8192===(this.mode&61440)}},createNode(a,b,c,d){a=new G.wb(a,b,c,d);nb(a);return a},ab(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isFIFO(a){return 4096===(a&61440)},isSocket(a){return 49152===(a&49152)},yb:4096,Ib:a=>G.streams[a],Bb:{open(a){a.qa=
G.Hb(a.node.rdev).qa;a.qa.open?.(a)},wa(){throw new G.oa(70);}},bb:a=>a>>8,hc:a=>a&255,Ga:(a,b)=>a<<8|b,Hb:a=>G.mb[a],ub(a,b){function c(l){G.Ta--;return b(l)}function d(l){if(l){if(!d.Eb)return d.Eb=!0,c(l)}else++g>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);G.Ta++;1<G.Ta&&p(`warning: ${G.Ta} FS.syncfs operations in flight at once, probably just doing extra work`);var e=vb(G.root.sa),g=0,h;for(h of e)h.type.ub?h.type.ub(h,a,d):d(null)},sa(a,b,c){var d="/"===c;if(d&&G.root)throw new G.oa(10);
if(!d&&c){var e=S(c,{Qa:!1});c=e.path;e=e.node;if(e.Ba)throw new G.oa(10);if(!K(e.mode))throw new G.oa(54);}b={type:a,Ma:b,qb:c,Pa:[]};a=a.sa(b);a.sa=b;b.root=a;d?G.root=a:e&&(e.Ba=b,e.sa&&e.sa.Pa.push(b));return a},Rb(a){a=S(a,{Qa:!1});if(!a.node.Ba)throw new G.oa(28);a=a.node;var b=a.Ba,c=vb(b);for([,e]of Object.entries(G.Da))for(;e;){var d=e.Ia;c.includes(e.sa)&&bb(e);var e=d}a.Ba=null;a.sa.Pa.splice(a.sa.Pa.indexOf(b),1)},lookup(a,b){return a.pa.lookup(a,b)},Aa(a,b,c){var d=S(a,{parent:!0}).node;
a=F(a);if(!a)throw new G.oa(28);if("."===a||".."===a)throw new G.oa(20);var e=pb(d,a);if(e)throw new G.oa(e);if(!d.pa.Aa)throw new G.oa(63);return d.pa.Aa(d,a,b,c)},ib(a){return wb(S(a,{za:!0}).node)},mc(a){return wb(a.node)},create(a,b=438){return G.Aa(a,b&4095|32768,0)},mkdir(a,b=511){return G.Aa(a,b&1023|16384,0)},ic(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{G.mkdir(d,b)}catch(g){if(20!=g.xa)throw g;}}},symlink(a,b){if(!Qa(a))throw new G.oa(44);var c=
S(b,{parent:!0}).node;if(!c)throw new G.oa(44);b=F(b);var d=pb(c,b);if(d)throw new G.oa(d);if(!c.pa.symlink)throw new G.oa(63);return c.pa.symlink(c,b,a)},rename(a,b){var c=La(a),d=La(b),e=F(a),g=F(b);var h=S(a,{parent:!0});var l=h.node;h=S(b,{parent:!0});h=h.node;if(!l||!h)throw new G.oa(44);if(l.sa!==h.sa)throw new G.oa(75);var m=L(l,e);a=Ra(a,d);if("."!==a.charAt(0))throw new G.oa(28);a=Ra(b,c);if("."!==a.charAt(0))throw new G.oa(55);try{var k=L(h,g)}catch(n){}if(m!==k){b=K(m.mode);if(e=qb(l,e,
b))throw new G.oa(e);if(e=k?qb(h,g,b):pb(h,g))throw new G.oa(e);if(!l.pa.rename)throw new G.oa(63);if(m.Ba||k&&k.Ba)throw new G.oa(10);if(h!==l&&(e=R(l,"w")))throw new G.oa(e);bb(m);try{l.pa.rename(m,h,g),m.parent=h}catch(n){throw n;}finally{nb(m)}}},rmdir(a){var b=S(a,{parent:!0}).node;a=F(a);var c=L(b,a),d=qb(b,a,!0);if(d)throw new G.oa(d);if(!b.pa.rmdir)throw new G.oa(63);if(c.Ba)throw new G.oa(10);b.pa.rmdir(b,a);bb(c)},readdir(a){a=S(a,{za:!0}).node;return rb(a.pa.readdir,54)(a)},unlink(a){var b=
S(a,{parent:!0}).node;if(!b)throw new G.oa(44);a=F(a);var c=L(b,a),d=qb(b,a,!1);if(d)throw new G.oa(d);if(!b.pa.unlink)throw new G.oa(63);if(c.Ba)throw new G.oa(10);b.pa.unlink(b,a);bb(c)},readlink(a){a=S(a).node;if(!a)throw new G.oa(44);if(!a.pa.readlink)throw new G.oa(28);return a.pa.readlink(a)},stat(a,b){a=S(a,{za:!b}).node;return rb(a.pa.ua,63)(a)},fstat(a){var b=U(a);a=b.node;var c=b.qa.ua;b=c?b:a;c??=a.pa.ua;rb(c,63);return c(b)},lstat(a){return G.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?
S(a,{za:!c}).node:a;yb(null,a,b,c)},lchmod(a,b){G.chmod(a,b,!0)},fchmod(a,b){a=U(a);yb(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?S(a,{za:!d}).node:a;ub(null,a,{timestamp:Date.now(),Wa:d})},lchown(a,b,c){G.chown(a,b,c,!0)},fchown(a){a=U(a);ub(a,a.node,{timestamp:Date.now(),Wa:!1})},truncate(a,b){if(0>b)throw new G.oa(28);a="string"==typeof a?S(a,{za:!0}).node:a;zb(null,a,b)},ec(a,b){a=U(a);if(0>b||0===(a.flags&2097155))throw new G.oa(28);zb(a,a.node,b)},pc(a,b,c){a=S(a,{za:!0}).node;rb(a.pa.va,
63)(a,{atime:b,mtime:c})},open(a,b,c=438){if(""===a)throw new G.oa(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");a=S(a,{za:!(b&131072),Ob:!0});d=a.node;a=a.path}var g=!1;if(b&64)if(d){if(b&128)throw new G.oa(20);}else{if(e)throw new G.oa(31);d=G.Aa(a,c|511,0);g=!0}if(!d)throw new G.oa(44);8192===(d.mode&61440)&&(b&=-513);
if(b&65536&&!K(d.mode))throw new G.oa(54);if(!g&&(e=d?40960===(d.mode&61440)?32:K(d.mode)&&("r"!==ob(b)||b&576)?31:R(d,ob(b)):44))throw new G.oa(e);b&512&&!g&&G.truncate(d,0);b&=-131713;b=sb({node:d,path:kb(d),flags:b,seekable:!0,position:0,qa:d.qa,Qb:[],error:!1});b.qa.open&&b.qa.open(b);g&&G.chmod(d,c&511);return b},close(a){if(null===a.fd)throw new G.oa(8);a.Xa&&(a.Xa=null);try{a.qa.close&&a.qa.close(a)}catch(b){throw b;}finally{G.streams[a.fd]=null}a.fd=null},wa(a,b,c){if(null===a.fd)throw new G.oa(8);
if(!a.seekable||!a.qa.wa)throw new G.oa(70);if(0!=c&&1!=c&&2!=c)throw new G.oa(28);a.position=a.qa.wa(a,b,c);a.Qb=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new G.oa(28);if(null===a.fd)throw new G.oa(8);if(1===(a.flags&2097155))throw new G.oa(8);if(K(a.node.mode))throw new G.oa(31);if(!a.qa.read)throw new G.oa(28);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new G.oa(70);b=a.qa.read(a,b,c,d,e);g||(a.position+=b);return b},write(a,b,c,d,e,g){if(0>d||0>e)throw new G.oa(28);
if(null===a.fd)throw new G.oa(8);if(0===(a.flags&2097155))throw new G.oa(8);if(K(a.node.mode))throw new G.oa(31);if(!a.qa.write)throw new G.oa(28);a.seekable&&a.flags&1024&&G.wa(a,0,2);var h="undefined"!=typeof e;if(!h)e=a.position;else if(!a.seekable)throw new G.oa(70);b=a.qa.write(a,b,c,d,e,g);h||(a.position+=b);return b},Ha(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new G.oa(2);if(1===(a.flags&2097155))throw new G.oa(2);if(!a.qa.Ha)throw new G.oa(43);if(!b)throw new G.oa(28);
return a.qa.Ha(a,b,c,d,e)},La(a,b,c,d,e){return a.qa.La?a.qa.La(a,b,c,d,e):0},$a(a,b,c){if(!a.qa.$a)throw new G.oa(59);return a.qa.$a(a,b,c)},readFile(a,b={}){b.flags=b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&z(`Invalid encoding type "${b.encoding}"`);var c=G.open(a,b.flags);a=G.stat(a).size;var d=new Uint8Array(a);G.read(c,d,0,a,0);"utf8"===b.encoding&&(d=Sa(d));G.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=G.open(a,c.flags,c.mode);"string"==
typeof b&&(b=new Uint8Array(Va(b)));ArrayBuffer.isView(b)?G.write(a,b,0,b.byteLength,void 0,c.Zb):z("Unsupported data type");G.close(a)},cwd:()=>G.lb,chdir(a){a=S(a,{za:!0});if(null===a.node)throw new G.oa(44);if(!K(a.node.mode))throw new G.oa(54);var b=R(a.node,"x");if(b)throw new G.oa(b);G.lb=a.path},jb(){G.Da=Array(4096);G.sa(I,{},"/");G.mkdir("/tmp");G.mkdir("/home");G.mkdir("/home/web_user");Ab();Bb();G.Fb={MEMFS:I,NODEFS:O,WORKERFS:Q}},Oa(a,b,c){G.Za=!0;a?G.Fa("/dev","stdin",a):G.symlink("/dev/tty",
"/dev/stdin");b?G.Fa("/dev","stdout",null,b):G.symlink("/dev/tty","/dev/stdout");c?G.Fa("/dev","stderr",null,c):G.symlink("/dev/tty1","/dev/stderr");G.open("/dev/stdin",0);G.open("/dev/stdout",1);G.open("/dev/stderr",1)},lc(){G.Za=!1;for(var a of G.streams)a&&G.close(a)},cc(a,b){try{var c=S(a,{za:!b});a=c.path}catch(g){}var d=!1,e=null;try{c=S(a,{parent:!0}),F(a),c=S(a,{za:!b}),d=!0,e=c.node}catch(g){}return d?e:null},$b(a,b){a="string"==typeof a?a:kb(a);for(b=b.split("/").reverse();b.length;){var c=
b.pop();if(c){var d=D(a+"/"+c);try{G.mkdir(d)}catch(e){if(20!=e.xa)throw e;}a=d}}return d},Fa(a,b,c,d){a=Na("string"==typeof a?a:kb(a),b);b=cb(!!c,!!d);var e;(e=G.Fa).bb??(e.bb=64);e=G.Ga(G.Fa.bb++,0);Ya(e,{open(g){g.seekable=!1},close(){d?.buffer?.length&&d(10)},read(g,h,l,m){for(var k=0,n=0;n<m;n++){try{var q=c()}catch(w){throw new G.oa(29);}if(void 0===q&&0===k)throw new G.oa(6);if(null===q||void 0===q)break;k++;h[l+n]=q}k&&(g.node.atime=Date.now());return k},write(g,h,l,m){for(var k=0;k<m;k++)try{d(h[l+
k])}catch(n){throw new G.oa(29);}m&&(g.node.mtime=g.node.ctime=Date.now());return k}});return xb(a,b,e)},Cb(a,b,c,d,e){class g{gb=!1;Sa=[];eb=void 0;tb=0;rb=0;get(k){if(!(k>this.length-1||0>k)){var n=k%this.chunkSize;return this.eb(k/this.chunkSize|0)[n]}}Pb(k){this.eb=k}vb(){var k=new XMLHttpRequest;k.open("HEAD",c,!1);k.send(null);200<=k.status&&300>k.status||304===k.status||z("Couldn't load "+c+". Status: "+k.status);var n=Number(k.getResponseHeader("Content-length")),q,w=(q=k.getResponseHeader("Accept-Ranges"))&&
"bytes"===q;k=(q=k.getResponseHeader("Content-Encoding"))&&"gzip"===q;var t=1048576;w||(t=n);var E=this;E.Pb(T=>{var Z=T*t,N=(T+1)*t-1;N=Math.min(N,n-1);if("undefined"==typeof E.Sa[T]){var Ub=E.Sa;Z>N&&z("invalid range ("+Z+", "+N+") or no bytes requested!");N>n-1&&z("only "+n+" bytes available! programmer error!");var J=new XMLHttpRequest;J.open("GET",c,!1);n!==t&&J.setRequestHeader("Range","bytes="+Z+"-"+N);J.responseType="arraybuffer";J.overrideMimeType&&J.overrideMimeType("text/plain; charset=x-user-defined");
J.send(null);200<=J.status&&300>J.status||304===J.status||z("Couldn't load "+c+". Status: "+J.status);Z=void 0!==J.response?new Uint8Array(J.response||[]):Va(J.responseText||"");Ub[T]=Z}"undefined"==typeof E.Sa[T]&&z("doXHR failed!");return E.Sa[T]});if(k||!n)t=n=1,t=n=this.eb(0).length,ma("LazyFiles on gzip forces download of the whole file when length is accessed");this.tb=n;this.rb=t;this.gb=!0}get length(){this.gb||this.vb();return this.tb}get chunkSize(){this.gb||this.vb();return this.rb}}if(globalThis.XMLHttpRequest){ba||
z("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");var h=new g;var l=void 0}else l=c,h=void 0;var m=Cb(a,b,d,e);h?m.ra=h:l&&(m.ra=null,m.url=l);Object.defineProperties(m,{ta:{get:function(){return this.ra.length}}});a={};for(const [k,n]of Object.entries(m.qa))a[k]=(...q)=>{Db(m);return n(...q)};a.read=(k,n,q,w,t)=>{Db(m);k=k.node.ra;if(t>=k.length)n=0;else{w=Math.min(k.length-t,w);if(k.slice)for(var E=0;E<w;E++)n[q+E]=k[t+E];else for(E=
0;E<w;E++)n[q+E]=k.get(t+E);n=w}return n};a.Ha=()=>{Db(m);z();throw new G.oa(48);};m.qa=a;return m}};function Eb(a,b){if("/"===b.charAt(0))return b;a=-100===a?G.cwd():U(a).path;if(0==b.length)throw new G.oa(44);return a+"/"+b}
var Ja=void 0,Fb=[0,31,60,91,121,152,182,213,244,274,305,335],Gb=[0,31,59,90,120,151,181,212,243,273,304,334],Hb={},Ib=a=>{if(a instanceof za||"unwind"==a)return oa;fa(1,a)},Jb=a=>{oa=a;fa(a,new za(a))},Kb=a=>{if(!na)try{a()}catch(b){Ib(b)}},Lb={},Nb=()=>{if(!Mb){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Lb)void 0===Lb[b]?delete a[b]:a[b]=Lb[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);
Mb=c}return Mb},Mb;G.ac=(a,b,c,d,e,g,h,l,m,k)=>{lb(a,b,c,d,e,l,m,k).then(g).catch(h)};G.kc=lb;G.jb();ca&&O.jb();f.callMain=Ob;f.ENV=Lb;f.FS=G;f.NODEFS=O;f.WORKERFS=Q;
var Pb,Qb,V,Ga,W,Rb,X,Sb,Tb,Ha,Vb,ua,Y,qc={n:(a,b,c,d)=>z(`Assertion failed: ${A(a)}, at: `+[b?A(b):"unknown filename",c,d?A(d):"unknown function"]),m:a=>{var b=new Fa(a);0==r[b.ya+12]&&(r[b.ya+12]=1,Ea--);r[b.ya+13]=0;Da.push(b);Tb(a);return Vb(a)},o:()=>{V(0,0);var a=Da.pop();Sb(a.nb);B=0},d:()=>Ia([]),i:a=>Ia([a]),K:(a,b)=>Ia([a,b]),B:()=>{var a=Da.pop();a||z("no exception to throw");var b=a.nb;0==r[a.ya+13]&&(Da.push(a),r[a.ya+13]=1,r[a.ya+12]=0,Ea++);B=b;throw B;},a:(a,b,c)=>{(new Fa(a)).Oa(b,
c);B=a;Ea++;throw B;},R:()=>Ea,f:a=>{B||=a;throw B;},w:function(a,b,c){Ja=c;try{var d=U(a);switch(b){case 0:var e=C();if(0>e)break;for(;G.streams[e];)e++;return tb(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=C(),d.flags|=e,0;case 12:return e=C(),ra[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(g){if("undefined"==typeof G||"ErrnoError"!==g.name)throw g;return-g.xa}},D:function(a,b,c){Ja=c;try{var d=U(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;
if(d.tty.Ea.Jb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=C();v[e>>2]=25856;v[e+4>>2]=5;v[e+8>>2]=191;v[e+12>>2]=35387;for(var g=0;32>g;g++)r[e+g+17]=a[g]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.Ea.Kb)for(e=C(),a=[],g=0;32>g;g++)a.push(r[e+g+17]);return 0;case 21519:if(!d.tty)return-59;e=C();return v[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:return e=
C(),G.$a(d,b,e);case 21523:if(!d.tty)return-59;d.tty.Ea.Lb&&(g=[24,80],e=C(),ra[e>>1]=g[0],ra[e+2>>1]=g[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(h){if("undefined"==typeof G||"ErrnoError"!==h.name)throw h;return-h.xa}},E:function(a,b,c,d){Ja=d;try{b=A(b);b=Eb(a,b);var e=d?C():0;return G.open(b,c,e).fd}catch(g){if("undefined"==typeof G||"ErrnoError"!==g.name)throw g;return-g.xa}},V:function(a,b,c,d){try{return b=A(b),d=A(d),b=Eb(a,b),d=Eb(c,d),
G.rename(b,d),0}catch(e){if("undefined"==typeof G||"ErrnoError"!==e.name)throw e;return-e.xa}},U:function(a,b){try{a=A(a);var c=G.stat(a);x[b>>2]=c.dev;x[b+4>>2]=c.mode;x[b+8>>2]=c.nlink;x[b+12>>2]=c.uid;x[b+16>>2]=c.gid;x[b+20>>2]=c.rdev;y[b+24>>3]=BigInt(c.size);v[b+32>>2]=4096;v[b+36>>2]=c.blocks;var d=c.atime.getTime(),e=c.mtime.getTime(),g=c.ctime.getTime();y[b+40>>3]=BigInt(Math.floor(d/1E3));x[b+48>>2]=d%1E3*1E6;y[b+56>>3]=BigInt(Math.floor(e/1E3));x[b+64>>2]=e%1E3*1E6;y[b+72>>3]=BigInt(Math.floor(g/
1E3));x[b+80>>2]=g%1E3*1E6;y[b+88>>3]=BigInt(c.ino);return 0}catch(h){if("undefined"==typeof G||"ErrnoError"!==h.name)throw h;return-h.xa}},T:function(a,b,c){try{b=A(b);b=Eb(a,b);if(c)if(512===c)G.rmdir(b);else return-28;else G.unlink(b);return 0}catch(d){if("undefined"==typeof G||"ErrnoError"!==d.name)throw d;return-d.xa}},Q:()=>z(""),O:()=>{},M:()=>{throw Infinity;},W:function(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);v[b>>2]=a.getSeconds();v[b+4>>2]=a.getMinutes();
v[b+8>>2]=a.getHours();v[b+12>>2]=a.getDate();v[b+16>>2]=a.getMonth();v[b+20>>2]=a.getFullYear()-1900;v[b+24>>2]=a.getDay();var c=a.getFullYear();v[b+28>>2]=(0!==c%4||0===c%100&&0!==c%400?Gb:Fb)[a.getMonth()]+a.getDate()-1|0;v[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();v[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},P:(a,b)=>{Hb[a]&&(clearTimeout(Hb[a].id),delete Hb[a]);if(!b)return 0;
var c=setTimeout(()=>{delete Hb[a];Kb(()=>Qb(a,performance.now()))},b);Hb[a]={id:c,oc:b};return 0},H:(a,b,c,d)=>{var e=(new Date).getFullYear(),g=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();x[a>>2]=60*Math.max(g,e);v[b>>2]=Number(g!=e);b=h=>{var l=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(g);b=b(e);e<g?(H(a,u,c,17),H(b,u,d,17)):(H(a,u,d,17),H(b,u,c,17))},F:()=>Date.now(),S:a=>{var b=u.length;
a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-ua.buffer.byteLength+65535)/65536|0;try{ua.grow(d);ta();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1},Y:(a,b)=>{var c=0,d=0,e;for(e of Nb()){var g=b+c;x[a+d>>2]=g;c+=H(e,u,g,Infinity)+1;d+=4}return 0},Z:(a,b)=>{var c=Nb();x[a>>2]=c.length;a=0;for(var d of c)a+=Ua(d)+1;x[b>>2]=a;return 0},t:a=>{oa=a;Jb(a)},C:function(a){try{var b=
U(a);G.close(b);return 0}catch(c){if("undefined"==typeof G||"ErrnoError"!==c.name)throw c;return c.xa}},$:function(a,b,c,d){try{a:{var e=U(a);a=b;for(var g,h=b=0;h<c;h++){var l=x[a>>2],m=x[a+4>>2];a+=8;var k=G.read(e,r,l,m,g);if(0>k){var n=-1;break a}b+=k;if(k<m)break;"undefined"!=typeof g&&(g+=k)}n=b}x[d>>2]=n;return 0}catch(q){if("undefined"==typeof G||"ErrnoError"!==q.name)throw q;return q.xa}},X:function(a,b,c,d){b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 61;
var e=U(a);G.wa(e,b,c);y[d>>3]=BigInt(e.position);e.Xa&&0===b&&0===c&&(e.Xa=null);return 0}catch(g){if("undefined"==typeof G||"ErrnoError"!==g.name)throw g;return g.xa}},_:function(a,b,c,d){try{a:{var e=U(a);a=b;for(var g,h=b=0;h<c;h++){var l=x[a>>2],m=x[a+4>>2];a+=8;var k=G.write(e,r,l,m,g);if(0>k){var n=-1;break a}b+=k;if(k<m)break;"undefined"!=typeof g&&(g+=k)}n=b}x[d>>2]=n;return 0}catch(q){if("undefined"==typeof G||"ErrnoError"!==q.name)throw q;return q.xa}},G:Wb,c:Xb,b:Yb,l:Zb,r:$b,J:ac,z:bc,
p:cc,x:dc,v:ec,y:fc,I:gc,h:hc,g:ic,e:jc,j:kc,k:lc,L:mc,q:nc,s:oc,u:pc,A:a=>a,N:Jb};function Yb(a,b,c){var d=X();try{return Y.get(a)(b,c)}catch(e){W(d);if(e!==e+0)throw e;V(1,0)}}function Xb(a,b){var c=X();try{return Y.get(a)(b)}catch(d){W(c);if(d!==d+0)throw d;V(1,0)}}function cc(a,b,c,d,e,g,h){var l=X();try{return Y.get(a)(b,c,d,e,g,h)}catch(m){W(l);if(m!==m+0)throw m;V(1,0)}}function jc(a,b,c){var d=X();try{Y.get(a)(b,c)}catch(e){W(d);if(e!==e+0)throw e;V(1,0)}}
function ic(a,b){var c=X();try{Y.get(a)(b)}catch(d){W(c);if(d!==d+0)throw d;V(1,0)}}function hc(a){var b=X();try{Y.get(a)()}catch(c){W(b);if(c!==c+0)throw c;V(1,0)}}function Zb(a,b,c,d){var e=X();try{return Y.get(a)(b,c,d)}catch(g){W(e);if(g!==g+0)throw g;V(1,0)}}function mc(a,b,c,d,e,g){var h=X();try{Y.get(a)(b,c,d,e,g)}catch(l){W(h);if(l!==l+0)throw l;V(1,0)}}function kc(a,b,c,d){var e=X();try{Y.get(a)(b,c,d)}catch(g){W(e);if(g!==g+0)throw g;V(1,0)}}
function $b(a,b,c,d,e){var g=X();try{return Y.get(a)(b,c,d,e)}catch(h){W(g);if(h!==h+0)throw h;V(1,0)}}function lc(a,b,c,d,e){var g=X();try{Y.get(a)(b,c,d,e)}catch(h){W(g);if(h!==h+0)throw h;V(1,0)}}function bc(a,b,c,d,e,g){var h=X();try{return Y.get(a)(b,c,d,e,g)}catch(l){W(h);if(l!==l+0)throw l;V(1,0)}}function fc(a,b,c,d,e,g){var h=X();try{return Y.get(a)(b,c,d,e,g)}catch(l){W(h);if(l!==l+0)throw l;V(1,0)}}
function ac(a,b,c,d,e,g){var h=X();try{return Y.get(a)(b,c,d,e,g)}catch(l){W(h);if(l!==l+0)throw l;V(1,0)}}function gc(a,b,c){var d=X();try{return Y.get(a)(b,c)}catch(e){W(d);if(e!==e+0)throw e;V(1,0)}}function dc(a,b,c,d,e,g,h,l){var m=X();try{return Y.get(a)(b,c,d,e,g,h,l)}catch(k){W(m);if(k!==k+0)throw k;V(1,0)}}function nc(a,b,c,d,e,g,h,l){var m=X();try{Y.get(a)(b,c,d,e,g,h,l)}catch(k){W(m);if(k!==k+0)throw k;V(1,0)}}
function ec(a,b,c,d,e,g,h,l,m,k,n,q){var w=X();try{return Y.get(a)(b,c,d,e,g,h,l,m,k,n,q)}catch(t){W(w);if(t!==t+0)throw t;V(1,0)}}function oc(a,b,c,d,e,g,h,l,m,k,n){var q=X();try{Y.get(a)(b,c,d,e,g,h,l,m,k,n)}catch(w){W(q);if(w!==w+0)throw w;V(1,0)}}function pc(a,b,c,d,e,g,h,l,m,k,n,q,w,t,E,T){var Z=X();try{Y.get(a)(b,c,d,e,g,h,l,m,k,n,q,w,t,E,T)}catch(N){W(Z);if(N!==N+0)throw N;V(1,0)}}function Wb(a,b,c){var d=X();try{return Y.get(a)(b,c)}catch(e){W(d);if(e!==e+0)throw e;V(1,0)}}
function Ob(a=[]){var b=Pb;a.unshift(ea);var c=a.length,d=Rb(4*(c+1)),e=d,g;for(g of a){a=x;var h=e>>2,l=g,m=Ua(l)+1,k=Rb(m);H(l,u,k,m);a[h]=k;e+=4}x[e>>2]=0;try{var n=b(c,d);oa=n;Jb(n);return n}catch(q){return Ib(q)}}
function rc(a=da){if(0<gb)hb=rc;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;){var b=f.preRun.shift();Aa.push(b)}for(;0<Aa.length;)Aa.shift()(f);0<gb?hb=rc:(f.calledRun=!0,na||(sa=!0,f.noFSInit||G.Za||G.Oa(),sc.ba(),G.Ya=!1,pa?.(f),f.noInitialRun||Ob(a)))}}var sc;
sc=await (async function(){var a={a:qc};va??=f.locateFile?f.locateFile?f.locateFile("qpdf.wasm",ia):ia+"qpdf.wasm":(new URL("qpdf.wasm",import.meta.url)).href;a=sc=(await ya(a)).instance.exports;Pb=f._main=a.ca;Qb=a.ea;V=a.fa;Ga=a.ga;W=a.ha;Rb=a.ia;X=a.ja;Sb=a.ka;Tb=a.la;Ha=a.ma;Vb=a.na;ua=a.aa;Y=a.da;ta();return sc}());rc();
Object.assign(G,{init:G.Oa,mkdir:G.mkdir,mount:G.sa,unlink:G.unlink,unmount:G.Rb,chdir:G.chdir,stat:G.stat,rmdir:G.rmdir,writeFile:G.writeFile,readFile:G.readFile,createLazyFile:G.Cb,setIgnorePermissions:function(a){G.Ya=a}});sa?moduleRtn=f:moduleRtn=new Promise((a,b)=>{pa=a;qa=b});
;return moduleRtn}export default Module;
